timApp/auth/accesshelper.py, timApp/tests/server/test_plugins.py, tim_common/markupmodels.py
#2638 https://timdevs01-3.it.jyu.fi/view/accesfield
- tehtävä voi katsoa oman laillisuutensa fieldistä
Lisää yleisen attribuutin accesField:
accessField:
field: kenttä jota katsotaan
limit: minimi numeroarvo, jolla estetään vastaaminen
error: Oma virheviesti
Oli pohdintaa myös siitä että pitäisikö tuossa olla enemmän mahdollisia sääntöjä: https://github.com/TIM-JYU/TIM/issues/2638#issuecomment-1159405099
Tuota pitäisi periaatteessa voida laajentaa vaihtamalla limit vapaaehtoiseksi attribuutiksi ja lisäämällä muita aliattribuutteja, mutta jos tuohon lukitsevaan fieldiin kirjoitetaan kuitenkin alkuun jsrunnerin tai vastaavan arvosteluskriptin kautta, niin minusta tähän ei kannata ainakaan alkuun laittaa heti alkuun kovin monimutkaista logiikkaa.
=> Accessfield

timApp/admin/util.py, timApp/auth/access/routes.py, timApp/auth/access/util.py, timApp/document/docentry.py, timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/markdown/markdownconverter.py, timApp/messaging/timMessage/routes.py, timApp/sisu/sisu.py, timApp/static/scripts/tim/header/role-info.component.ts, timApp/static/scripts/tim/item/access-role.service.ts, timApp/static/scripts/tim/item/active-group-lock-dialog/active-group-lock-dialog.component.scss, timApp/static/scripts/tim/item/active-group-lock-dialog/active-group-lock-dialog.component.ts, timApp/static/scripts/tim/item/active-group-lock-dialog/showGroupLockDialog.ts, timApp/static/scripts/tim/user/IUser.ts, timApp/static/scripts/tim/user/user-menu.component.ts, timApp/tests/db/test_users.py, timApp/tests/server/test_access_lock.py, timApp/tests/server/test_default_rights.py, timApp/tests/server/test_permissions.py, timApp/tests/server/test_scim.py, timApp/user/groups.py, timApp/user/user.py, timApp/user/usergroup.py
Lisää käyttäjämenuun oikeuksien lukitus/rajoituspainikkeen (ks #537):
Tämä avaa rajoitusdialogin, jossa oma ryhmäjäsenyys voi väliaikaisesti rajoittaa:
Asettamalla ruksit eri tavalla voidaan testata eri dokumenttien toimintaa ja näkyvyyttä erilaisilla ryhmillä. 
Huomiot:
* Ryhmäjäsenyyden rajoittaminen pätee vain oikeuksiin (oikeus nähdä dokumentit, oikeus vastata tehtäviin, oikeus tehdä muita toimintoja). Rajoitus ei muuta todellista jäsenyyden tilaa.
* Ryhmäjäsenyys voi rajoittaa ryhmiin, johon kuulut tai johon sinulla on **vähintään edit-oikeus**
* Tehokkuussyistä **edit**-oikeudelliset ryhmät ei näytetä suoraan. Sen sijaan dialogissa on hakulaatikko, jonka kautta ryhmät voi lisätä listaan.
* Admin voi hakea ryhmien lisäksi käyttäjien henkilökohtaiset ryhmät
Esimerkki: …
=> Add active group switch dialog (#537)

timApp/auth/access/routes.py, timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/static/scripts/tim/item/active-group-lock-dialog/active-group-lock-dialog.component.ts, timApp/user/groups.py
Kaksi pientä muutosta aktiivisten ryhmien lukitusdialogiin:
* Anonymous users ei näytetä enää ryhmälukitusdialogissa. Sen sijaan kyseinen ryhmä on aina mukana lukituksessa. Tämä näin, koska käytännössä kaikki käyttäjät perivät aina kyseisen ryhmän oikeudet.
* Omat ryhmät jaetaan nyt erikseen "hallituihin" ja "hallitsemattomiin". Hallitut ryhmät ovat ne, joilla on hallintadokumentti olemassa (esim. käsin tehdyt ryhmät, "aktivoidut" sisuryhmät). 
Tämä PR liittyy korttiin #3078
=> Improve UI of group locking (closes #3078)

timApp/plugin/timtable/timTable.py, timApp/static/scripts/tim/plugin/tim-table-editor-toolbar-dialog.component.ts, timApp/static/scripts/tim/plugin/timTable.ts
Lisää alustavan mahdollisuuden lisätä uusia rivejä/sarakkeida TimTable-tehtäviin. Tämä onnistuu lisäämällä `taskCanModifyTable`-attribuutti. Ominaisuus mahdollistaa esim. ilmoittautumistaulukkoiden tekemistä, jotka voi sitten käsitellä JSRunnerilla.
Tässä alustavassa toteutuksessa sarakkeita ja rivejä ei voi lisätä/poistaa mielivaltaisesta paikasta vielä (vaatii vähän laajemman logiikan, jossa otetaan huomioon markuppiin laitetut solut sekä perusmuodossa että datablock-muodossa). Tämä logiikka kuitenkin ottaa huomioon lukitut sarakkeet sekä markuppiin laitetut rivit ja sarakkeet poiston yhteydessä.
Esimerkki: <https://timdevs01-2.it.jyu.fi/view/users/dz-dz/test-timtable-task-rowadd>
=> Add initial ability to add/remove rows in task TimTable

timApp/static/scripts/tim/velp/velpSelection.ts, timApp/tests/server/test_velp.py, timApp/velp/velp.py, timApp/velp/velpgroups.py
Raise a RouteException if trying to create a velp group for the document using the 'Document' option (as opposed to 'Personal' or 'Folder'). <s>A further solution could be to default to the 'Folder' option if the document has no owners (lines 718-725 in velp.py).</s>
Interface will show a message dialog informing the user of the error (document has no owner). At this time, no further action is taken, since most users will never encounter this problem.
Resolves issue #2618.
=> Add preliminary fix for creating velp groups for ownerless documents

timApp/answer/routes.py, timApp/auth/accesshelper.py, timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/item/manage.py, timApp/item/taskblock.py, timApp/plugin/plugin.py, timApp/plugin/pluginControl.py, timApp/static/scripts/tim/answer/answerbrowser3.ts, timApp/static/scripts/tim/plugin/attributes.ts, timApp/static/templates/answerBrowser.html, tim_common/markupmodels.py
https://timdevs01-3.it.jyu.fi/view/modelanswer_mr
Ensimmäinen versio mallivastauksesta. Lisää uuden yleisen pluginattribuutin
```
modelAnswer:
answer: Mallivastaus tekstinä (tukee md)
linkText: Mallivastauksen linkki
lock: true # (oletus, mallin katsomisen jälkeen vastaukset ovat invalid)
lockText: varmistus ennen vastauksen lukitsemista
count: 2 # yritysten vähimmäismäärä, valinnainnen
```
Tällä hetkellä käytetään taskBlock-taulua ja blockAccess-taulua tarkistamaan onko vastausta lukittu. Tässä on huonona puolena se että kantaan ei jää selkeää infoa siitä miksi tehtävä on lukittu. Jos käyttää accessDuration-attribuuttia (tai tulevaisuudessa tulee muita tapoja lukita yksittäinen tehtävä), ei ole mitään tapaa tutkia kannasta että tämä lukitus tuli mallivastauksen katsomisen vuoksi tms
=> Modelanswer

timApp/static/stylesheets/velpSelection.scss
Small fix to annotation pop-ups being too big because of .fulldiv-style used in the template.
=> Fix annotation size

pyproject.toml, timApp/velp/annotation.py, timApp/velp/annotation_model.py, timApp/velp/velp.py, timApp/velp/velp_folders.py, timApp/velp/velp_models.py, timApp/velp/velpgroups.py, timApp/velp/velps.py
Fix typings/type annotations for velp source files (timApp/velp/*.py).
TODO:
**Ignored for now, no type hints available.**
**Mostly fixed in #3093.**
**Refactored.**
**Refactored, still uses dicts for json_responses for now because of UI code dependencies.**
- <s>Convert Blueprints to TypedBlueprints (and refactor remaining dicts into TypedDicts or dataclasses?)</s> Move into its own PR.
=> Fix velp typings

timApp/document/docsettings.py, timApp/static/scripts/tim/answer/answerbrowser3.ts, timApp/static/scripts/tim/document/IDocSettings.ts, timApp/static/scripts/tim/plugin/attributes.ts, timApp/static/templates/answerBrowser.html, tim_common/markupmodels.py
>Melkein tekisi mieli että olisi dokumenttikohtainen asetus, jolla
voisi antaa oletusarvoja "kaikille" AB:n teksteille/valinnoille.
Esim tuo showValidOnly on sellainen, mikä useimiten tekisi mieli muuttaa
koko dokumentissa.  Ja tietty siksi esim demojen tapauksessa sen preamblessa.
Lisää uuden dokumenttiasetuksen
```
answerBrowser:
pointsStep: sama kuin lokaali pointsstep
validOnlyText: Oletusteksti "Show valid only"n tilalle
showValidOnly: Oletusasetus show valid -ruksille
```
https://timdevs01-3.it.jyu.fi/teacher/answerbrowser-globals
Samat asetukset toimii myös lokaalisti yksittäisellä pluginilla. Käytännössä saman asian voisi antaa global_plugin_attrsina, joten mietityttää vähän onko erillisessä dokuasetuksessa järkeä.
=> Answerbrowser globals

timApp/answer/answers.py, timApp/answer/feedbackanswer.py, timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/static/scripts/tim/answer/all-answers-dialog.component.ts, timApp/static/scripts/tim/document/viewctrl.ts, timApp/static/scripts/tim/util/globals.ts
Toteuttaa puuttuvat `group`-argumentin toiminnon poluille `allAnswersPlain` ja `allDocumentAnswersPlain`. Lisää samalla raporttidialogiin radiobuttonin, jolla voi rajata vastaukset kaikkiin vastaajiin tai sitten "dokumenttiryhmään" (eli ryhmä, joka määritelty `group`-dokumenttiasetuksessa).
Katso #2637
=> Add group argument to allAnswersPlain and allDocumentAnswersPlain (closes #2637)

timApp/answer/answers.py
Korjaa #2591. JSON-muotoinen tuloste tottelee samoja asetuksia kuin tekstimuotoinen tuloste.
Lisäksi muokkaa JSON-muotoa siten, että kaikkien kenttien tyyppi on aina sama riippumatta asetuksista. Eli esim. pseudonymisointi ei muuta `user`-objektin tyyppiä `object`:sta `string`:ksi. Tämä helpottaa jatkossa JSONin parsimista ulkoisissa ohjelmissa.
=> Fix JSON answer reports not respecting output options (closes #2591)

timApp/answer/routes.py, timApp/plugin/pluginControl.py, timApp/static/scripts/tim/answer/IAnswer.ts, timApp/static/scripts/tim/answer/answerbrowser3.ts, timApp/static/scripts/tim/plugin/attributes.ts, timApp/tests/server/test_plugins.py, tim_common/markupmodels.py
Poistaa mallivastaukseen liittyvän käsittelylogiikan pluginifystä, ja hakee mallivastauksen tiedot answerbrowserin taskInfo-reitissä
https://timdevs01-3.it.jyu.fi/view/modelanswer_lazy
Aiemmissa stresstest-mittauksissa 100 ohj1-monisteella ajat olivat ~43 sek ilman lukkoja, ~1min37 sek lukoilla. Nyt ~36
Normaali ohj1:
```
avg 35.0495
[sijualle@timdevs01 tim3]$ for i in {1..4}; do ./tim tool stress-test --calls 100 502; done
real    0m35.181s
user    0m0.443s
sys     0m1.077s
Errors: 0
real    0m33.894s
user    0m0.393s
sys     0m0.841s
Errors: 0
real    0m35.914s
user    0m0.423s
sys     0m1.028s
Errors: 0
real    0m35.209s
user    0m0.428s
sys     0m0.984s
Errors: 0
```
Ohj1, modelAnswer jokaisessa tehtävässä lukoilla:
```
avg 35.73725
[sijualle@timdevs01 tim3]$ for i in {1..4}; do ./tim …
```
=> Modelanswer lazy

timApp/plugin/calendar/calendar.py, timApp/static/scripts/tim/plugin/calendar/calendar.component.ts, timApp/static/scripts/tim/plugin/calendar/timeviewselector.component.ts, timApp/static/scripts/tim/util/utils.ts
Ensimmäinen satsi nopeita refaktorointeja ja lisäyksiä kalenteriin:
* Lisää 120 min aikasegmentin
* Lisää `viewOptions`-asetuksen markuppiin, jolla voi valita oletusasetukset kalenterin alalaidassa oleviin näkyvyysasetuksiin:
```yaml
viewOptions:               # Default view options for the calendar
dayStartHour: 8        # Time at which the day starts (0-24)
dayEndHour: 20         # Time at which the day ends (0-24)
segmentDuration: 60    # Duration of a single time segment (a selectable slot in calendar) in minutes. Allowed values: 15, 20, 30, 60, 120
```
* Muutettu hieman oletusarvoja: nyt oletuskoko aikasegmentille on 60 min, niin kalenteri ei paisu liian korkeaksi heti alkuun
* Lisää pari templatea lohkoeditoriin (`Plugin -> Calendar`), niin ei tarvitse etsiä pohja ohjeista
* …
=> Calendar: Add 120 minute segments, add view options to markup, add plugin templates

timApp/answer/routes.py, timApp/auth/accesshelper.py, timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/plugin/plugin.py, timApp/static/scripts/tim/answer/IAnswer.ts, timApp/static/scripts/tim/answer/answerbrowser3.ts, timApp/static/scripts/tim/document/viewctrl.ts, timApp/static/scripts/tim/plugin/attributes.ts, timApp/static/scripts/tim/plugin/taskid.ts, timApp/static/templates/answerBrowser.html, tim_common/markupmodels.py
Lisää uuden yleisen pluginattribuutin tehtävien ketjutusta varten
https://timdevs01-3.it.jyu.fi/view/previoustask
```
class PreviousTaskInfo:
taskid: str # pakollinen
requireLock: bool | None | Missing = False # Jos true niin edellinen tehtävä pitää olla lukittu modelAnswerin kautta (löytyy taskBlock ja umpeen mennyt blockAccess)
count: int | None | Missing = missing # Kuinka monta vastausyritystä edellisessä tehtävässä pitää olla.
hide: bool | None | Missing = missing # piilotetaanko tehtävä jos ehdot ei täyty
hideText: str | None | Missing = missing # Teksti piilotetun tehtävän paikalla 
unlockText: str | None | Missing = missing # Painiketeksti piilotetun tehtävän kohdalla
unlockError: str | None | Missing = missing # Virheviesti jos yrittää avata piilotettua tehtävää, jota ei saa …
```
=> Previoustask

timApp/plugin/plugin.py, timApp/static/scripts/tim/answer/answerbrowser3.ts
Piilottaa tai näyttää alueita (vain css) niihin liittyvien piiloutuvien pluginien mukaan
Piiloutuvat pluginit katsovat käynnistyessään alueet, joilla on hide-with attribuutti jossa on sama taskid kuin pluginilla, ja piilottavat / näyttävät ne sen mukaan onko plugin itse piilotettu
https://timdevs01-3.it.jyu.fi/view/previoustask-hide
Sama dokumentti, mutta myös itse plugin on piiloutuvan alueen sisällä:
https://timdevs01-3.it.jyu.fi/view/hide-within-task
=> Previoustask area

timApp/answer/routes.py, timApp/plugin/plugin.py, timApp/static/scripts/tim/answer/answerbrowser3.ts, timApp/static/scripts/tim/answer/reset-task-lock-dialog-component.ts, timApp/static/scripts/tim/answer/showResetTaskLock.ts, timApp/static/templates/answerBrowser.html
Alustava ui taskBlockien poistamiseen (=asetetaan blockAccessissa accessible_to nulliksi). Mallivastauslinkin viereen tulee poistolinkki, josta voi (toistaiseksi manuaalisesti nimellä) valita kenen blockAccess tyhjenee
Testuser1:llä omistuisoikeus, muilla view: https://timdevs01-3.it.jyu.fi/view/previoustask-hide
=> Add method to clear task blocks

timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/modules/cs/js/editor/module.ts, timApp/plugin/calendar/calendar.py, timApp/plugin/calendar/models.py, timApp/static/scripts/tim/plugin/calendar/calendar.component.scss, timApp/static/scripts/tim/plugin/calendar/calendar.component.ts, timApp/static/scripts/tim/plugin/calendar/custom-event-title-formatter.service.ts, timApp/static/scripts/tim/plugin/calendar/edit-json-event-dialog.component.ts, timApp/static/scripts/tim/plugin/calendar/showEditJsonEventDialog.ts, timApp/tests/server/test_calendar.py, tim_common/timjsonencoder.py
Lisää yksinkertaisen massamuokkauksen JSONin kautta.
Toiminta:
* Avaa kalenterin edit-tila
* Exportin viereen ilmestyy uusi painike:
* Painikkeesta painaminen avaa saman kalenterin *samoilla filtteriasetuksilla* JSON-muodossa
* Tapahtumien muokkaus, lisäys ja poisto onnistuu odotetusti (jos id paikalla, tehdään muokkaus; jos idtä ei ole, luodaan uusi tapahtuma)
* Tapahtuman poisto onnistuu lisäämällä `"delete": true` tapahtumaan (dialogissa on tästä vinkki)
* Tällä hetkellä filtteröinti tehdään kalenterin markupin perusteella
Testi: https://timdevs01-2.it.jyu.fi/view/users/test-user-1/test-extrabookers (testuser1, se omistaa kaikki tapahtumat)
Tämä mergetään vasta #3134 jälkeen.
=> Calendar: Add mass editing

timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/static/scripts/tim/answer/IAnswer.ts, timApp/static/scripts/tim/answer/answerbrowser3.ts, tim_common/markupmodels.py
Lisää vielä yhden attribuutin modelAnsweriin
hideText: Teksti jota painamalla avattu mallivastaus. Oletuksena lokalisoitu "Piilota mallivastaus" 
https://timdevs01-3.it.jyu.fi/view/modelanswer_tex
=> Add separate text for hiding model answer

timApp/answer/routes.py, timApp/markdown/markdownconverter.py
Katsotaan modelAnswer-reitissä kappaleen dumbo-asetukset, jotta esim `math_type: svg` toimii mallivastauksessa oikein
https://timdevs01-3.it.jyu.fi/view/modelanswer_tex
=> Check dumbo options when viewing model answer

tim_common/markupmodels.py
PluginDateTime-kentissä (esim deadlinet tai modelAnswerin revealDate) hyväksytään paremmin eri aikamuodot
https://timdevs01-3.it.jyu.fi/view/deadline
=> Use dateutil.parser in PluginDateTime

timApp/answer/routes.py, timApp/markdown/markdownconverter.py
Mahdollistaa {%raw%} ja {%endraw%} tagit mallivastauksessa
>Miten saan mallivastaukseen "raakaa koodia" sillä tavalla ettei mene makroista selaisin
https://timdevs01-3.it.jyu.fi/view/modelanswer-raw
=> Model answer raw

timApp/answer/routes.py, tim_common/markupmodels.py
Kolme uutta attribuuttia modelAnsweriin:
disabled: estää avaamisen kokonaan
endDate: Aikaleima jonka jälkeen avaaminen estetään
groups: ryhmät joille vastaus voidaan antaa ( * = vastanneet, tyhjä taulukko = avoin kaikille)
https://timdevs01-3.it.jyu.fi/view/modelanswer-limits
=> ModelAnswer: add disabled, endDate and groups attributes

timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/static/scripts/tim/document/editing/editing.ts, timApp/static/scripts/tim/ui/showTemplateReplaceDialog.ts
Closes #3158 
Lisää `.addTemplateAbove` ja `.addTemplateBelow` -luokat. Ne toimivat samalla tavalla kuin nykyiset `.addAbove` ja `.addBelow`, mutta editorin avaamisen sijaan niillä avataan vain yksinkertainen dialogi.
Esimerkki: https://timdevs01-5.it.jyu.fi/view/users/test-user-1/test-addpar
=> Add addTemplateAbove and addTemplateBelow

caddy/Caddyfile, cli/commands/test.py, cli/templates/.idea/runConfigurations/Test.xml, cli/templates/.idea/runConfigurations/_template__of_Autodetect.xml, cli/templates/docker/docker-compose.tmpl.yml, cli/util/template.py, timApp/testconfig.py
Closes #3157
Muuttaa testien ajokonfiguraatiota niin, että 
* `tests`-kontti on aina käytettävissä dev-profiilissa
* PyCharm-testit ajetaan `tests`-kontissa
Tämä mahdollistaa testien ajamisen eristyksessä pääkontista, mikä voi helpottaa tiettyä kehitystä. 
Tämä PR myös päivittää PyCharmin oletuskonfiguraatiot, mutta jo olemassa olevissa asennuksissa ne pitää päivittää käsin seuraavasti:
* Lisää `tests`-kontin interpreter [PyCharm-ohjeiden mukaisesti](https://tim.jyu.fi/view/tim/TIMin-kehitys/PyCharm#interpreter)
* Muuta Testauskonfiguraation aktiivista interpreteria (Python interpreter -kohta) `tests`-kontin interpreteriksi
=> Use `tests` container for tests in dev

timApp/static/scripts/tim/document/structure/parContext.ts, timApp/static/scripts/tim/document/structure/parsing.ts, timApp/static/scripts/tim/ui/draggable.ts, timApp/static/stylesheets/style.scss, timApp/templates/partials/paragraphs.jinja2
Closes #3170 
Lisää hyvin yksinkertaisen ja alustavan tuen kelluville lohkoille.
Toimintaperiaate: lohkolle tai alueelle lisätään `float="true"`. Dialogin otsikkoa voi muuttaa attribuutilla `float_caption="Otsikko"` 
Tällä hetkellä toteutus on yksinkertainen mutta riittänee SUKOLin tarkoitukseen:
* Käyttää vanhoja AngularJS-dialogeja, joilla on erilaisia tunnetuja bugeja (mutta AngularJS-dialogit toimivat parhaiten yksinkertaisessa toteutuksessa)
* Muutokset tehty Jinja2-pohjiin, mikä sekoittaa koodia hieman
* collapsible-alueet eivät vielä toimi täydellisesti
Esimerkki: https://timdevs01-2.it.jyu.fi/view/users/test-user-1/test-float-par
=> Add basic floating paragraph support

timApp/static/scripts/tim/plugin/calendar/calendar.component.scss
Sets the min-width css property for the 'middle' button of the view scroller to prevent its arrow buttons from 'jumping' around when the middle button resizes itself.
The exact size is adjustable under *btn-outline-secondary* in `calendar.component.scss`.
| Before | After |
|:--------|:------|
| ![before1](https://user-images.githubusercontent.com/46485327/189368610-42acba43-50c2-4423-890d-2e13b96f1d8b.png) | ![after1](https://user-images.githubusercontent.com/46485327/189368601-3dd5137f-9054-4b25-8d8a-3752d5809421.png) |
| ![before2](https://user-images.githubusercontent.com/46485327/189368611-f3881f50-9453-4384-b5fd-4030d9b66e05.png) | ![after2](https://user-images.githubusercontent.com/46485327/189368608-30e65d9a-9c41-48a8-b7a8-bf88e543355e.png) |
=> Set min-width for day/week/month scroller

timApp/modules/drag/client/drag.ts
The 'max' option for the drag plugin was not working because of calling removed or deprecated external directive. This pull request fixes the issue by calling the correct directive.
=> Fix drag plugin 'max' option

timApp/upload/upload.py
Varmistaa että yli 10-sivuiset pdf-palautukset latautuvat reviewcanvaksessa oikeassa järjestyksessä. Esimerkiksi omassa lokaalissa tim-asennuksessa os.listdir saa tiedostonimet järjestyksessä `image-1, image-10, image-2...`, eli sivu 10 tulee palautuksessa ennen sivua 2
Tuotantotimissä ja timdevsissä näyttäisi palautuvan valmiiksi oikeassa järjestyksessä, mutta se on kuitenkin parempi muuttaa niin että järjestys on oikein koneesta riippumatta.
=> Sort reviewCanvas pdf pages correctly

timApp/plugin/qst/qst.py, timApp/static/scripts/tim/plugin/qst.component.ts, timApp/tests/browser/test_lecture.py, timApp/tests/server/test_question.py
Muuttaa downgradetetun qst-komponentin nimeksi "tim-lecture-qst", jotta pluginloader ei yrittäisi ladata väärää versiota qst:stä. Tällä hetkellä downgradetetun version lataaminen aiheuttaa virheitä konsolissa:
Tavallinen qst pluginLoaderissa: https://timdevs01-3.it.jyu.fi/view/qst_normi
Luentoversio: https://timdevs01-3.it.jyu.fi/lecture/qst-lecture
=> Fix non-pluginloader qst complaining about ngZone

timApp/static/scripts/tim/answer/pluginLoader.ts
Tarkistaa onko pluginloaderin sisällä mitään ladattavaa komponenttia
Esim showInView saattaa aiheuttaa sen, että sivulla on pluginloader, mutta sen sisällä on pelkkää kommenttitekstiä.
https://timdevs01-3.it.jyu.fi/view/hiddenplugin vs https://tim.jyu.fi/view/users/sijualle/kokeiluja/hiddenplugin
=> Handle empty pluginLoader

timApp/modules/cs/js/csPlugin.ts, timApp/modules/cs/js/editor/editor.ts, timApp/modules/cs/js/editor/normal.ts, timApp/static/scripts/tim/plugin/attributes.ts, tim_common/markupmodels.py
https://timdevs01-3.it.jyu.fi/view/cs-spellcheck
Yleinen spellcheck-pluginattribuutti, toistaiseksi käytetään vain cspluginin yhdessä tapauksessa (myöhemmin varmaan ainakin textfieldissä / qst tekstibokseissa jne)
Lisää textareaan attribuutin spellcheck="arvo" jos spellcheck on annettu. Jos ei annettu niin koko attribuuttia ei ole ja selaimet toimii omilla oletuksillaan.
=> Add common spellcheck plugin attr, implement on cs textArea

timApp/modules/drag/client/drag.ts, timApp/modules/drag/drag_main.py, timApp/modules/fields/dropdown.py, timApp/modules/fields/js/dropdown-plugin.component.ts, timApp/modules/fields/js/numericfield-plugin.component.ts, timApp/modules/fields/js/textfield-plugin.component.ts, timApp/modules/fields/numericfield.py, timApp/modules/fields/textfield.py, timApp/plugin/plugin.py, timApp/static/scripts/tim/plugin/util.ts
Lisää dragille ja dropdownille tuen styles-arvolle, jolloin niitä voi värjätä tableformin (tai jsrunnerin) kautta
Lisäksi lisää samat väriattribuutit kuin mitä textfield/numericfield käytti jo aiemmin eli
- ignorestyles: kenttä ei värjäydy vaikka styles-arvossa on jotain (jos esim tableFormilla merkitsee vastauksia eikä halua sekoittaa vastaajia), oletus false
- clearstyles: värit katoaa kun vastaaja tekee uuden vastauksen. Normaalisti väri on pysyvä, eli tableformin kautta pysyvä värimerkintä ei katoa vaikka tekee uuden vastauksen. Oletus false
https://timdevs01-3.it.jyu.fi/view/dragdropstyles
=> Dragdrop styles

timApp/static/stylesheets/stylesheet.scss
Applies the `toggle-margin-left` to the main content strip `.paragraphs` with the DIA mini stylesheet so the sidebarmenu's content align button works.
=> Enable toggle margin left in DIA-mini style

timApp/static/scripts/tim/document/question/questions.ts, timApp/static/scripts/tim/lecture/question-preview-dialog.component.ts, timApp/static/scripts/tim/plugin/qst.component.ts
Päivittää qst-kappaletta ilman tarvetta sivun uudelleenlautukselle vaikka muutokset tehtäisiin qst-pluginin (?-merkki) kautta. Tällä hetkellä ne päivittyvät heti vain jos qst:n muokkaus tehdään "edit question"-painikkeen kautta
https://timdevs01-3.it.jyu.fi/lecture/qst-lecture
vs 
https://tim.jyu.fi/lecture/users/sijualle/kokeiluja/qstlec
=> Qst dialogresult

timApp/plugin/tableform/tableForm.py, timApp/static/scripts/tim/plugin/tableForm/table-form.component.ts, timApp/static/scripts/tim/plugin/timTable/tim-table-editor-toolbar-dialog.component.ts, timApp/static/scripts/tim/plugin/timTable/tim-table.component.ts, timApp/static/scripts/tim/plugin/timTable/toolbarUtils.ts, timApp/tests/browser/test_tableform.py, timApp/tests/browser/test_timtable.py
https://timdevs01-3.it.jyu.fi/view/tableform_save
Muuttaa timTablen solun tallennuslogiikkaa niin että solun muutokset hyväksytään automaattisesti mikäli pieni editori suljetaan siirtämällä focus johonkin toiseen elementtiin sivulla. Tämä ei ole yhtä vahva autosavelogiikka kuin textfieldillä, jossa kenttä tallennetaan esim osoiteriville siirtymisestä.
Lisäksi pieni optimointi sille ettei tableFormissa haeta rivejä turhaan mikäli taulukkoa ei ole vaan plugin on vain reporttipainiketta varten.
=> Table savefocus

timApp/markdown/markdownconverter.py
Fix rare encoding bug in MD to HTML parsing by changing lxml's etree.tostring()'s encoding scheme from default ASCII to UTF-8.
The bug has already been reported at <https://bugs.launchpad.net/lxml/+bug/1945048>, but it will likely not be resolved any time soon.
=> Fix rare encoding bug in MD to HTML parsing

timApp/modules/cs/js/jsframe.ts, timApp/modules/cs/jsframe.py, timApp/modules/cs/jsframehtml/simpleDrawIO.html
Muokkaa drawion latauslogiikkaa niin että iframen html:ssä ei viedä piirrosdataa, sillä esim chrome tuntuu luovuttavan jos iframen src-attribuutti on liian pitkä. Sen sijaan piirrosdata viestitään iframelle vasta sen käynnistyttyä
https://timdevs01-3.it.jyu.fi/view/drawio-image
=> Drawio setdata

timApp/plugin/plugin.py, timApp/tests/browser/test_inlineplugins.py, timApp/tests/server/test_plugins.py
Lisää drag-pluginin `NEVERLAZY_PLUGINS`iin, lisäksi muuttaa kaikki inlinepluginit latautumaan normaalisti vaikka pluginien määrärajoitus tai dokumentin asetus haluaisi ne laiskana. Voi ohittaa jos antaa erikseen pluginille markupissa lazy: true (tosin ei vielä korjausta sille että inlinessä laiskat pluginit hajoaa, https://github.com/TIM-JYU/TIM/issues/3227#issuecomment-1315192571)
https://timdevs01-3.it.jyu.fi/view/lazyinline
=> Don't load drag or inline plugins as lazy

timApp/auth/accesshelper.py, timApp/tests/server/test_jsrunner.py, timApp/tests/server/test_plugins.py
Muuttaa accessFieldiä (=tehtävän lukitseminen toisen tehtävän vastauksen avulla) niin että lukitsevasta kentästä tarkistetaan vain validit vastaukset.
https://timdevs01-3.it.jyu.fi/view/accessfield_points
vrt
https://tim.jyu.fi/view/users/sijualle/kokeiluja/accessfield_points
Ylin checkbox on accessField, ja sen validia arvoa ei pitäisi voida muuttaa muulla kuin erikseen tarjotuilla jsrunnereilla.
Lisäksi testi sille että answerLimit 0 voidaan ohittaa jsrunnerilla. Myöhemmin tarvinnee jonkun järkevämmän tavan tehdä kenttä jonka syöte saadaan vain opettajan tarjoamien jsrunnerien kautta, mutta tällä hetkellä tuotannossa on pari kurssia joiden tehtävissä nojataan tuon kikan varaan.
=> Accessfield invalid

timApp/static/templates/velpSelection.html
Lisää Velp menun templateen .hidden-print bootstrap-tyylin, joka piilottaa Velp menun näkyvistä dokumenttia tulostaessa.
=> Hide Velp menu when printing the document

timApp/static/scripts/tim/plugin/tim-menu/tim-menu-plugin.component.scss, timApp/static/scripts/tim/plugin/tim-menu/tim-menu-plugin.component.ts, timApp/static/scripts/tim/user/user-menu.component.ts
Menujen pientä viilausta
- timmenu/kirjautumismenu ei sulje enää jo avattua valikkoa jos siirtää kursorin saman valikon kohdalle
- kirjautumismenussa alivalikon (lock access) voi avata myös kosketusnäytöllä
- timmenussa ei tarvitse enää painaa kosketusnäytöllä kahdesti jotta alivalikot aukeaa
- timmenu ei tule enää yläpalkin tielle jos skrollaa ylös liian nopeasti
https://timdevs01-3.it.jyu.fi/view/timmenu
vrt
https://tim.jyu.fi/view/users/sijualle/kokeiluja/timmenu
=> Menu hover

timApp/answer/routes.py, timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/modules/fields/js/textfield-plugin.component.ts, timApp/plugin/pluginControl.py, timApp/static/scripts/tim/answer/answer-browser.component.ts, timApp/static/scripts/tim/plugin/plugin-loader.component.ts, timApp/static/templates/answerBrowser.html, timApp/tests/browser/test_answerbrowser.py, timApp/tests/browser/test_teacher.py, timApp/tests/server/test_plugins.py
Korjaa bugin jossa globaali kenttä harmaantui jos kirjautuneella käyttäjällä ei ollut vastauksia kentässä jsrunnerin/tableformin kautta tulevassa kentän päivityksessä, ja toteuttaa iänikuisen tipin ajoilta jääneen todon siitä että globaalissa kentässä voisi selata vastauksia.
https://timdevs01-3.it.jyu.fi/teacher/global_updatefield (kannattaa kirjautua admin1:llä) vs https://tim.jyu.fi/teacher/users/sijualle/kokeiluja/global_updatefield
Korjaa myös #3278
https://timdevs01-3.it.jyu.fi/teacher/validonlybug vs https://tim.jyu.fi/teacher/users/sijualle/kokeiluja/validonlybug
Lisäksi tehtävän harmaantumiselle pientä viilausta (opettajannäkymässä harmaantuu johdonmukaisemmin aina jos ei vastauksia ellei save techer's fix ruksittu), ja textfieldin rows-attribuutti vaikuttaa taas textArean …
=> Update global and invalid answer browsing

timApp/static/scripts/tim/answer/answer-browser.component.ts, timApp/static/templates/answerBrowser.html
Korjaa bugin jossa modelanswer-attribuutti, joka pakottaa valid only-ruksin pois päältä, saa answerbrowserin näyttämään väärää vastausten lukumäärää
https://timdevs01-3.it.jyu.fi/view/modelanswer-validonly vs https://tim.jyu.fi/view/users/sijualle/kokeiluja/modelanswer-validonly
Lisäksi view-näkymässä ei puhuta enää "valitusta käyttäjästä"
=> Fix modelanswer valid answer count, don't call current view user "selected user"

timApp/static/stylesheets/style.scss
Fixes `draggable-block`s being initialized to (almost) 100% of window width when they are detached from the document.
=> Set default width for draggable-block

timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/modules/cs/js/csPlugin.ts, timApp/modules/cs/js/jsframe.ts, timApp/modules/cs/js/stack.ts, timApp/modules/cs/js/util/file-select.ts, timApp/modules/drag/client/drag.ts, timApp/modules/feedback/js/feedback.ts, timApp/modules/fields/js/cbcountfield-plugin.component.ts, timApp/modules/fields/js/cbfield-plugin.component.ts, timApp/modules/fields/js/dropdown-plugin.component.ts, timApp/modules/fields/js/goaltable-plugin.component.ts, timApp/modules/fields/js/multisave.ts, timApp/modules/fields/js/numericfield-plugin.component.ts, timApp/modules/fields/js/rbfield-plugin.component.ts, timApp/modules/fields/js/textfield-plugin.component.ts, timApp/modules/jsrunner/client/javascripts/jsrunner-plugin.component.ts, timApp/modules/svn/js/images.component.ts, timApp/modules/svn/js/video.component.ts, timApp/static/scripts/tim/document/viewctrl.ts, timApp/static/scripts/tim/plugin/angular-plugin-base.directive.ts, timApp/static/scripts/tim/plugin/calendar/calendar.component.ts, timApp/static/scripts/tim/plugin/imagex/imagex.component.ts, timApp/static/scripts/tim/plugin/plugin-loader.component.ts, timApp/static/scripts/tim/plugin/qst/qst.component.ts, timApp/static/scripts/tim/plugin/reviewcanvas/review-canvas.component.ts, timApp/static/scripts/tim/plugin/tim-menu/tim-menu-plugin.component.ts, timApp/static/scripts/tim/util/utils.ts, timApp/tests/browser/test_csplugin.py, timApp/tests/browser/test_fields.py
Perusidea: kaikki pluginit laitetaan varoittamaan puuttuvasta task-id:stä.
Oletuksena kaikki `AngularPluginBase`n perivät pluginit varoittavat mikäli task-id puuttuu. Jotkut plugintyypit (kuten showVideo tai jsframe ilman drawiota) eivät varoita. Tuota joutunee vielä kartoittamaan että löytyykö vielä plugineita joissa ei käytetä task-id:tä.
https://timdevs01-3.it.jyu.fi/view/no_tids
=> Add warnings about missing task ids

timApp/tests/browser/test_timtable.py
Parantaa timtablen focus-testiä niin että solua muokatessa odotetaan timtablen toolbarin aukeamista. Jos solun muokkauksen aloittaa tuplaklikkamalla robottinopeudella niin toolbar kerkeää aueta kahdesti ja sitten loput testistä hajoaa
=> Add a wait to prevent double toolbars in test_focus_callbacks

timApp/modules/fields/js/numericfield-plugin.component.ts, timApp/modules/fields/js/textfield-plugin.component.ts
Text- ja numericfield tottelee värimäärityksiään myös plaintext-näkymässä
https://timdevs01-3.it.jyu.fi/view/field-styles
=> Use field styles in plaintext mode

timApp/static/scripts/tim/ui/bootstrap-panel.component.ts, timApp/static/scripts/tim/user/settings.component.ts
Closes #3314 
Adds optional heading panel anchors to bootstrap panel component and utilizes these to add heading anchors to different section in TIM settings page.
=> UI settings heading anchors

timApp/answer/answers.py, timApp/answer/routes.py, timApp/document/course/validate.py, timApp/document/docsettings.py, timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/item/routes.py, timApp/peerreview/util/groups.py, timApp/sisu/sisu.py, timApp/static/scripts/tim/answer/all-answers-dialog.component.ts, timApp/static/scripts/tim/answer/answer-browser.component.ts, timApp/static/scripts/tim/answer/import-answers-dialog.component.ts, timApp/static/scripts/tim/document/viewctrl.ts, timApp/static/scripts/tim/util/globals.ts, timApp/templates/partials/doc_head.jinja2, timApp/tests/server/test_bookmarks.py, timApp/tests/server/test_groups.py, timApp/tests/server/test_plugins.py, timApp/tests/server/test_teacher.py
Lisää `groups`-dokumenttiasetuksen, johon voi listata dokumentin ryhmät taulukkona, ja muuttaa dokumenttien asetuslogiikkaa niin että ryhmät käsitellään aina listana ryhmiä. Vanha `group`-dokumenttiasetus käsitellään yhtenä groups-listan alkiona
Testi timdevs02:ssa, esim
https://timdevs02.it.jyu.fi/teacher/users/sijualle/csplug
Ryhmiä joilla voi leikkiä
https://timdevs02.it.jyu.fi/view/groups/timohjeet/mallikurssinryhma1
https://timdevs02.it.jyu.fi/view/groups/pahikset1
https://timdevs02.it.jyu.fi/view/groups/tim/hiiret1
https://timdevs02.it.jyu.fi/view/groups/testiryhmat/vainankat1
https://timdevs02.it.jyu.fi/view/groups/ankat1
https://timdevs02.it.jyu.fi/view/groups/ankanpojat1
=> Add groups docsetting, handle group as element of groups

timApp/defaultconfig.py, timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/static/scripts/tim/frontpage/front-page.component.ts, timApp/static/scripts/tim/user/haka-login.component.scss, timApp/static/scripts/tim/user/haka-login.component.ts, timApp/static/scripts/tim/user/login-dialog.component.scss, timApp/static/scripts/tim/user/login-dialog.component.ts, timApp/tests/browser/browsertest.py
Closes #3266 
Refactors the UI of TIM login so that the simple username/email login is hidden by default, and works exactly like the 'sign up' procedure.
Todo:
=> TIM login: refactor simple login to work like sign up

timApp/static/scripts/tim/messaging/tim-message-send.component.ts, timApp/static/scripts/tim/plugin/tableForm/table-form.component.ts
Closes #3317 
Toteuttaa #3317 (myös localstorage-osa, vaikka siitä olisi ollut parempi tehdä oma kortti). Tällä hetkellä localstoragen asetukset tallenetaan pluginkohtaisesti, koska eri plugineissa ehkä haluaa erilaiset oletusasetukset postien lähettämiselle.
Esimerkki: <https://timdevs01-2.it.jyu.fi/teacher/users/dz-dz/test-send-mail>
=> Improve message send component messages; save send options to local storage

timApp/answer/routes.py, timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/modules/fields/js/textfield-plugin.component.ts, timApp/modules/fields/textfield.py
Muuntaa userAnswersForTasks-reitissä kaikki md:-alkuiset vastaukset markdowniksi.
Pallottelin jonkin verran onko tuota järkevää tehdä itse tuossa reitissä (eli hidastaako se lomakkeiden käyttäjävaihtoa), ja testailin toisessa haarassa tilannetta jossa tuo md-kutsu tehdään tarvittaessa eri pyynnöllä. 
Devsissä on tuo testihaara ja tilanne jossa on 50 pitkää vastausta sisältävää tekstfieldiä
https://timdevs01-3.it.jyu.fi/teacher/50fields_form (muunnokset eri pyynnöllä, userAnswersForTasks ~150ms)
https://timdevs01-3.it.jyu.fi/teacher/50fields-noform-nomd (muunnokset samassa pyynnössä, muttei mitään muutettavaa userAnswersForTasks ~200ms)
https://timdevs01-3.it.jyu.fi/teacher/50fields-noform-nomd (muunnokset samassa ja 50x pitkää muutettavaa md-tekstivastausta, userAnswersForTasks ~750ms) …
=> Textfield md

timApp/answer/answers.py, timApp/document/docviewparams.py, timApp/item/routes.py, timApp/static/scripts/tim/answer/all-answers-dialog.component.ts, timApp/tests/browser/test_teacher.py, timApp/tests/server/test_plugins.py, timApp/util/utils.py
Korjaa ryhmäpäivityksessä hajonneet all answers / answers as plain text -painikkeet.
Lisäksi urlmacro group toimii useammalla pilkulla erotellulla ryhmällä. Groups toimii synonyyminä. Lisäksi jos antaa tyhjän &group= makron niin toimitaan kuin dokussa ei olisi ryhmäasetusta ollenkaan
https://timdevs01-3.it.jyu.fi/teacher/1csplug
Testiryhminä voi käyttää tu1pub, tu5pub jne
=> Group urlparam

timApp/velp/annotation.py
Piilottaa vertaisarvioijien nimet vaikka vertaisarviointi on jo päättynyt
=> Fix reviewer names showing after peer_review ends

timApp/modules/jsrunner/server/package-lock.json, timApp/modules/jsrunner/server/package.json, timApp/modules/jsrunner/server/routes/answer.ts, timApp/modules/jsrunner/server/routes/tools.ts, timApp/modules/jsrunner/server/tsconfig.json, timApp/modules/jsrunner/server/util/request.ts, timApp/static/scripts/tim/plugin/errors.ts
Lisää `tools.request`-funktion, jonka avulla JSRunner-skripteistä voi tehdä HTTP-kutsuja.
Tämän avulla onnistuu esim. vuorovaikutus GitLabin kanssa TIMista (esim. opiskelijoiden lisääminen ryhmään, yms). Toinen esimerkki on JetBrains-lisenssien antaminen käyttäjille.
Funktion dokumentaatio:
```ts
/**
* Performs an HTTP request.
*
* @param url URL to request
* @param opts Options for the request. The available options are:
*              - method: HTTP method to use (default: "GET")
*              - query: URL query parameters to add to the URL as a record [string, string] (default: undefined)
*              - headers: HTTP headers to send (default: {})
*              - timeout: Request timeout in milliseconds (default: 10000)
*              - body: Data to send with the request. This can …
```
=> jsrunner: Add tools.request

timApp/answer/answers.py, timApp/answer/routes.py, timApp/modules/cs/js/editor/ace.ts, timApp/static/scripts/tim/answer/answer-browser.component.ts, timApp/static/scripts/tim/editor/AceParEditor.ts, timApp/tests/server/test_answers.py, timApp/tests/server/test_plugins.py
Muuttaa answerLimit-asetuksen toimintaa niin että invalid-vastauksia ei lasketa käytettyihin yrityskertoihin.
Lisäksi ylimääräinen ctrl+' pikanäppäin, jolla voi firefoxilla muuttaa ace-editorissa maalatut koodirivit kommenteiksi #3347
https://timdevs01-3.it.jyu.fi/view/kooditehtava
=> Add extra ACE comment shortcut, ignore invalid answers when counting answerLimit

timApp/admin/fix_settings_references.py, timApp/document/docparagraph.py, timApp/document/docsettings.py, timApp/document/document.py, timApp/document/editing/routes.py, timApp/item/item.py, timApp/item/manage.py, timApp/modules/jsrunner/server/routes/answer.ts, timApp/modules/jsrunner/server/routes/tools.ts, timApp/modules/jsrunner/shared/jsrunnertypes.ts, timApp/plugin/jsrunner/util.py, timApp/user/userutils.py
Jatkoa PR:lle #3365 
Kortti on osa SUKOL-tehtäviä (#3199), joten tämä toteuttaa vain välttämättömät toiminnot saadakseen vaatimukset täytettyä.
Lisää `gtools.addItemRightAction`, jolla voi ohjelmallisesti antaa tai umpeuttaa dokumenttioikeuksia. 
Rajoitukset:
* Funktiolla ei voi antaa owner-oikeuksia välttääkseen väärinkäyttöä
* Kohdedokumentissa tulee olla asetettuna `manageKey`-dokumenttiasetus, jolla sallitaan oikeuksien muokkaamista. Tämä tehty välttääkseen JSRunnereiden väärinkäyttöä kunnes saadaan kehitettyä parempi järjestelmä pluginien oikeuksien hallintaan.
* Toistaiseksi tuetaan vain oikeuksien lisääminen ja umpeuttaminen, mikä riittää SUKOL-käyttöön. Jatkossa muutkin oikeustyypit sekä oikeuksien konfirmointi voitaisiin sallia.
Esimerkki: …
=> JSRunner: Add gtools.addItemRightAction

timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/static/scripts/tim/answer/answer-browser.component.ts, timApp/static/scripts/tim/header/header.component.ts, timApp/static/stylesheets/stylesheet.scss, timApp/static/templates/answerBrowser.html
Lisää selainpohjaisen matikkarenderöinnin vertaisarviointikenttiin. Tätä varten vertaisarviointinäkymässä on "preview"-valinta jolla voi esikatsella matikkaa. Tuota pitäisi myöhemmin hienosäätää niin että esikatselu sekä muokkaus olisivat selkeästi erinäköiset (esikatselu aukeaisi kelluvaan ikkunaan, erilainen tausta tms). Toistaikseksi vain selainrenderöinti, eli markdown ja svg-matikka pitää tehdä myöhemmin.
Lisäksi vertaisarviointinäkymässä ei lisätä enää b tai size -urlparametreja timin valikkolinkkeihin
https://timdevs01-3.it.jyu.fi/view/pr_input
=> Peerreview input UI

.github/workflows/format.yml, .github/workflows/lint.yml, .github/workflows/spellcheck.yml, .github/workflows/stats.yml, .github/workflows/tests.yml, cli/commands/dev/build.py, cli/commands/js.py, cli/config/config_file.py, cli/config/default_config.py, cli/templates/docker/docker-compose.tmpl.yml, cli/templates/docker/mailman.tmpl.yml, timApp/Dockerfile, timApp/modules/cs/csi.sh, timApp/modules/cs/languages.py, timApp/modules/cs/run.py, timApp/modules/cs/ur.sh, timApp/modules/cs/urs.sh, timApp/modules/cs/urss.sh, timApp/modules/cs/usrs.sh, timApp/tim.py
Tämä PR ottaa käyttöön GitHubin konttirekisterin ja siirtää kaikkien konttien pohjakuvat siihen Docker Hubista.
Docker Hub on sulkemassa ilmaiset organisaatiot (ks. tim-jyu/tim-private#70) ja jatkossa tarjoaa vain erillisellä haulla saatavat lisenssit. Lisäksi Docker Hubin ylläpito on ollut hankalaa, koska se sijaitsi erillään projektista (ja organisaation koko oli rajoitettu 3 tunnukseen).
Lisäksi PR tekee muutaman korjauksen CIhin nopeuttamaan ja parantamaan sen toimintaa.
Tämän PR:n muutokset:
* Kaikkien konttien pohjakuvat siirretty GitHubin konttirekisteriin. Jatkossa siis konttien nimi on muotoa `ghcr.io/tim-jyu/kontti` vanhan `timimages/kontti` sijaan. 
* Päivitetty TIM CLI osaamaan käsitellä uusi rekisteri. Täten peruskäytössä ei tarvitse välittää konttien sijainnista, vaan …
=> Migrate containers to GHCR

timApp/static/scripts/tim/answer/answer-browser.component.ts, timApp/static/scripts/tim/document/IDocSettings.ts, timApp/static/scripts/tim/plugin/attributes.ts, tim_common/markupmodels.py
Lisää saveTeacher-attribuutin joilla voi laittaa tehtävään valmiiksi Save teacher's fix -asetuksen päälle. Käyttötapauksena tilanne jossa opettaja käyttää tehtävää (esim tekstikenttää) kommentoimaan opiskelijan vastausta, vaikka answerbrowser on osittain piilotettuna.
Lisäksi vaihtaa save_teacher-dokumenttiasetuksen syntaksin vastaamaan tätä (tuo pitää käydä skriptillä vaihtamassa muutamassa dokumentista uuteen)
https://timdevs01-3.it.jyu.fi/teacher/saveteacher
=> Add saveTeacher markup attribute

timApp/answer/answers.py, timApp/answer/routes.py, timApp/document/docsettings.py, timApp/peerreview/util/groups.py, timApp/plugin/jsrunner/util.py, timApp/tests/server/test_peer_review.py
Lisää peer_review_allow_invalid-dokumenttiasetuksen, jonka myötä myös invalidit vastaukset otetaan myös vertaisarviointiparien generointiin mukaan. 
Lisäksi poistaa vaatimuksen opettajaoikeuksista mikäli jsrunnerilla käsitellään vertaisarviointidataa tai velppejä. Nuo ovat olleet piilossa lähinnä siksi että velpit ja vertaisarvioinnit haetaan yhtenä pötkönä, ja sitä kautta voi periaatteessa kurkkia velppejä tai vertaisarviointeja joita käyttäjä ei näkisi normaalisti ilman opettajaoikeutta. Mutta koska noita datoja haetaan toistaiseksi vain samasta dokumentista kuin itse jsrunner, noita käsitellessä voinee olettaa että jsrunnerin on tehnyt (ja jättänyt näkyville) joku jolla on vähintään edit-oikeus kyseiseen dokumenttin. Tämän myötä voi antaa vastaajan pyörittää esim jsrunnerin joka …
=> Allow PeerReview data in jsrunner without teacher rights, add peer_review_allow_invalid docsetting

timApp/i18n/messages.fi.xlf, timApp/item/manage.py, timApp/plugin/userselect/userselect.py, timApp/tests/server/test_velp.py
Closes #3400.
(This is a cherry-picked branch from [`velp-group-permissions`](https://github.com/TIM-JYU/TIM/tree/velp-group-permissions) that avoids conflicts due to 'dirty' branching)
Refactors setting velp group permissions, simplifies logging permissions.
=> Refactor velp group permissions

timApp/velp/annotation.py
- Poistaa anonymize_reviewers-asetuksen vaikutuksen vertaisarviointeihin. Nykytoteutuksella tuota ei voi käyttää vertaisarvioijien anonymisointiin, sillä vertaisarviointia varten on pakko tietää selaimessa arvioitavan käyttäjäid. Aiemmin tuo oli käytössä niin että arvioijan id piilotettiin, mutta jos arvioija sattui myös vertaisarvioitavaksi kohteeksi niin kohteen id piilotettiin myös, mikä rikkoi vertaisarviointia
- Piilottaa get_annotations-reitissä myös arvioitavan nimen, eikä vain arvioijan nimeä
=> Hide reviewable name

timApp/admin/global_notification.py, timApp/answer/routes.py, timApp/auth/accesshelper.py, timApp/defaultconfig.py, timApp/static/scripts/tim/answer/answer-browser.component.ts, timApp/static/scripts/tim/document/interceptor.ts, timApp/static/scripts/tim/plugin/angular-plugin-base.directive.ts, timApp/static/scripts/tim/plugin/import-data/import-data.component.ts, timApp/static/scripts/tim/plugin/mmcq/mmcq.ts, timApp/static/scripts/tim/plugin/reviewcanvas/review-canvas.component.ts, timApp/tests/server/test_late_answers.py, timApp/tests/server/test_plugins.py, tim_common/markupmodels.py
- Näyttää väärästä ip:stä tuleville varoituksen myös sisäänkirjautumisen jälkeen (myös admineille)
- Näyttää jokaisessa vastausyrityksessä ip-varoituksen (ei admineille)
- Toistaiseksi `Answering is not allowed from this IP address.`, ehkä parempi jos näyttäisi configin ip_block_messagea? 
- Answer-reitin onnistuneesta kutsusta voi tulla nyt useampi virhe, jotka kaikki näytetään erillisinä virheinä. 
Devsissä on muuten sama haara paitsi sähköpostivaroitukset poistettu
https://timdevs01-3.it.jyu.fi/view/answerlimit
=> Always warn about blocked ip

timApp/defaultconfig.py, timApp/plugin/userselect/action_queue.py, timApp/plugin/userselect/dist_right_util.py, timApp/plugin/userselect/userselect.py, timApp/plugin/userselect/utils.py, timApp/tests/server/test_userselect.py, timApp/tim_celery.py, timApp/util/logger.py, tim_common/collections.py
Tämä PR lisää UserSelect-komponenttiin `useActionQueues`-attribuutin, joka puskuroi ryhmä- ja oikeuslevitystoimintojen ajamista. Lisäksi pari pientä muutosta:
* Celerystä tulevat lokit merkitään `[CELERY]`-tagilla
* Lisätty `keydefaultdict`, joka toimii kuten `defaultdict`, mutta `default_factory` saa parametriksi avaimen, jolla alkio haettiin
Olennaisin puskuroinnin käyttötarkoitus ovat valtavat tentit, jossa tenttijöitä kirjataan sisään saliryhmiin UserSelectilla. Näissä tenteissa UserSelect on usein konfiguroitu seuraavasti:
```yaml
changeGroup:
changeTo: %%saliryhma%%
allGroups:
- sali1
- sali2
- sali3
verify: true
```
Kun tenttijä "piipataan" sisään UserSelectilla, yllä oleva esimerkki tomii seuraavasti:
* Tarkistetaan, kuuluuko tenttijä johonkin listattuun saliryhmään. Jos on, …
=> UserSelect: Speed up group and distribution action registering

timApp/answer/answers.py, timApp/tests/server/test_plugins.py, timApp/util/get_fields.py
Fixes #3389 
Salli oikeanlaisen tehtyjen tehtävien lukumäärän selvittämisen pisteryhmittelijästä käyttäen `tally:123.rule.task_count` ja `tally:123.rule.velped_task_count` -kenttiä. Tässä tapauksessa `task_count` kertoo, kuinka monta pisteryhmittelijän tehtävää käyttäjä on tehnyt ja `velped_task_count` kertoo, kuinka monessa pisteryhmittelijän tehtävää on velpattu.
Lisäksi korjaa bugin, jossa määritelmättömän pisteryhmittelijäkentän käyttö (esim. `tally:123.rule.joku`) palautti automaattisesti `total_points`.
Testi/esimerkki: <https://timdevs01-5.it.jyu.fi/view/users/test-user-1/test-tally-taskcount>
=> Add task_count support for pointsumrule tally

timApp/item/partitioning.py, timApp/item/routes.py, timApp/tests/server/test_peer_review.py, timApp/velp/annotation.py, timApp/velp/velp.py, timApp/velp/velpgroups.py
Korjaa tilanteen jossa vertaisarvioinnin käynnistäminen käännetyssä dokumentissa ei lisännyt vertaisarviointirivejä, sillä aiemmin käännetyissä kappaleissa ei osattu katsoa kunnolla mitä lohkoa tai aluetta käännöskappeleen osa vastaa alkuperäisessä dokumentissa.
https://timdevs01-3.it.jyu.fi/view/pr_translated/en
Lisäksi muuttaa velppien oletusryhmän tarkistamista niin että käännösdokumenteilla ja alkuperäisillä dokumenteilla on sama default velp group. Aiemmin käännösversiossa ei voinut edes luoda uutta velppipohjaa jos käännöksen default velp group oli valittuna, sillä se yritti luoda käännösdokumentille erillisen default velp groupin ja epäonnistui.
Vertaa uuden velppipohjan tekoa esim
https://timdevs01-3.it.jyu.fi/view/pr_translated/en ja …
=> Fix pr generation in translations

timApp/answer/routes.py, timApp/plugin/plugin.py, timApp/plugin/qst/qst.py, timApp/static/scripts/tim/answer/answer-browser.component.ts, timApp/tests/browser/test_model_answer.py, timApp/tests/server/test_inlineplugins.py, timApp/tests/server/test_plugins.py, tim_common/markupmodels.py, tim_common/pluginserver_flask.py
Lisää modelAnswer-attribuuttiin kaksi uutta aliattribuuttia
- hidePoints: jos true niin pisteet piilotetaan kunnes mallivastaus on katsottu
- minPoints: Pitää saada x pistettä että mallivastauksen voi avata
https://timdevs01-3.it.jyu.fi/view/modelanswer-points
Lisäksi userAnswersForTasks-reitissä ollut pisteiden kurkistelumahdollisuus on nyt tukittu
=> Modelanswer points attributes, hide points in userAnswersForTasks

timApp/static/tim_docs/initial/print_base.md, timApp/tests/server/expected/printing/hello_1_2.tex
Closes #1278.
Adds the (S)CSS styles `.troutofdate` and `.checktr` to the default TeX print template base. Previously, the in-built print functionality using TeX/LaTeX would fail because of missing style declarations.
Note that this change only affects new instances, since the default print template is created only once from the base file. Subsequent modifications need to be made by hand in a running instance by modifying the template file found in the 'TIM path' `[host]/view/templates/printing`.
=> Add translation warning styles to default TeX print template

timApp/static/scripts/tim/item/manageCtrl.ts, timApp/static/templates/manage.html
A small QOL improvement to the Translations-section of the Manage-page, adds direct links to a document's translations.
Closes #3441.
=> Add links to a document's translations to the Manage-page

timApp/static/scripts/tim/item/manageCtrl.ts
Force a documents aliases/page update when changing current document's language on the Manage page.
Resolves #3437.
=> Fix page links on doc lang change

timApp/document/post_process.py, timApp/tests/server/test_par_visibility.py
Muuttaa piilotettujen alueiden käsittelyä niin että sisäkkäisiä alueita ei prosessoida, mikäli ulompi alue on piilossa. Etenkin piilotettujen alueiden sisällä olevat collapsible-alueet eivät enää näytä tyhjää otsikkoa.
Aiemmin piilotettujen alueiden sisällä olevien alueiden alku- ja loppukohdat näkyivät, mutta itse kappaleiden sisältö ei näkynyt. En ollut varma oliko ne tarkoituksella vai ei (esim rikkinäisten alueiden helpompaa huomaamista varten). Laitoin kuitenkin nyt niin etteivät ne näy, mutta sen saa kohtuu nopeasti muutettua myös toisinpäin jos näin halutaan
https://timdevs01-3.it.jyu.fi/view/areabugi
=> Skip nested area processing if within hidden area

timApp/static/templates/manage.html
Adds missing id-attributes for (AngularJS) heading panel elements on the Manage page.
Chromium-based browsers (tested: Chrome, Vivaldi) still seem to behave weirdly -- it seems AngularJS elements' anchors can be activated only after an Angular component's heading anchor has been activated at least once.
Both Firefox and Chromium-based browser do not seem able to autoscroll the page onto the anchored element via an external link, but only when the page has been loaded normally and the anchor link is activated on the browser address bar. This affects  both AngularJS elements and Angular components. 
Bonus: (mostly) fix inconsistent formatting.
=> Fix heading anchors in Manage-page

timApp/plugin/taskid.py, timApp/tests/server/test_jsrunner.py, timApp/util/get_fields.py, timApp/util/plugininfofield.py
Closes #3429 
Lisää JSRunneriin uuden `plugininfo:`-kenttätyypin, joka kirjoitetaan muodossa
``` 
- plugininfo:group.count
``` 
Kenttätyyppi hakee plugineihin liittyviä tietoja suoraan JSRunnerin kenttiin. Kuten `tally:`, `plugininfo:` tukee pisteryhmittelijöitä sekä alikenttiä. Aliakset ovat tuettu kuten tallyssa ja peruskentissä.  Olennaisin käyttötarkoitus on hakea tietoa dokumentissa olevista plugineista JSRunneriin.
Yleinen syntaksi kentälle on on
``` 
plugininfo:[doc_id].[group].[field]
```
jossa
- `doc_id` (**valinnainen**) on dokumentin ID, josta pluginit haetaan. Jos puuttuu, dokumentin ID on tämänhetkisen avatun dokumentin ID.
- `group` (**valinnainen**) on pisteryhmittelijän nimi. Jos määritetty, kenttään haetaan vain pisteryhmittelijää vastaavat pluginit. Tällä tavoin pluginit …
=> JSRunner: Add plugininfo field type

timApp/document/document.py, timApp/document/editing/routes.py, timApp/item/partitioning.py, timApp/item/routes.py, timApp/tests/server/test_doc_partition.py
Korjaa tilanteen jossa dokumentit cacheutuvat väärin jos avaa muutosten jälkeen vain osan dokumentista
Vrt https://timdevs01-3.it.jyu.fi/view/visible?area=35 vs https://tim.jyu.fi/view/users/sijualle/kokeiluja/visible?area=35 (muokkaa jompaa kumpaa kappaletta ja f5)
Lisäksi liittää dokumentin asetuskappaleet dokumenttiin mikäli dokumentti avataan osissa (esim vain jokin area), jotta "set settings"-valikosta pystyisi aina muokkaamaan dokumentin asetuksia vaikka dokumentti on avattu vain osissa.
=> Improve partial document handling

timApp/modules/cs/js/csPlugin.ts
https://timdevs01-3.it.jyu.fi/view/parsonsdef#aliohjelmatValmiina vs https://tim.jyu.fi/view/users/sijualle/kokeiluja/parsonsdef#aliohjelmatValmiina -> Näytä koko koodi
=> csPlugin: use undefined parsons as default instead of {}

cli/commands/setup.py
Bump minimum Poetry version from 1.2.1 to 1.3.1. Current `poetry.lock` file has been generated by Poetry version >1.3, so earlier Poetry version can't read it (see <https://github.com/python-poetry/poetry/issues/7211>).
This PR brings the Poetry version to parity with the Dockerfile, and resolves the above issue with new TIM installations.
=> Bump Poetry min version from 1.2.1 to 1.3.1

timApp/document/docparagraph.py, timApp/document/documents.py, timApp/document/translation/synchronize_translations.py, timApp/templates/partials/paragraphs.jinja2, timApp/tests/server/test_plugins_preamble.py, timApp/tests/server/test_preview.py
Corrects the handling of cited paragraphs/citations when translating documents:
- preserve citations instead of converting them into regular translated paragraphs
- if the cited document has a same-language translation to the current translation, uses the translated citation (or the original if no corresponding translations exist)
Resolves #3405, resolves #3388, resolves #3465.
TODO:
- Area citations in translations should get the source translation's document id instead of the current (ie. citing) translation's base document.
- <s>ParRef reference for area citations is not correct</s>
**Known issues**:
1. there is a corner case where cited plugins from preambles do not find their correct tasks
- dedicated issue: #3464 
- will not be fixed in this PR
---
2. cite pars in translated …
=> Fix translation citation pars

timApp/plugin/plugin.py
Korjaa käyttäjän itse pisteyttämien tehtävien pisteiden validoinnin:
- muuntaa desimaalierottimen pilkkumuotoisesta pistemuotoiseen, jonka Python osaa muuntaa floatiksi
- ottaa huomioon tuhaterottimet siltä varalta, että joku niitä yrittää tarjota (tuskin on tarpeen, mutta estetään rikkoutuminen)
Testattavana: <https://timdevs01-6.it.jyu.fi/view/users/test-user-1/plugin-userpoints/a>
=> Fix validate_points to accept values with comma as decimal separator

timApp/admin/routes.py, timApp/tests/server/test_admin.py, timApp/user/user.py
Allows displaying user's group memberships in user search results with the `show_groups` URL parameter.
Accepted values are 'true' and 'True', all else is considered False.
=> Display user's groups in user search with URL param

timApp/static/scripts/tim/answer/answer-browser.component.ts
Poistaa show valid only-ruksin pois päältä pakottamisen jos ollaan opettajanäkymässä ja tehtävässä on mallivastaus
Jos tehtävässä on mallivastaus, siihen pakotetaan answerbrowseriin show valid only aina pois päältä, muistaakseni siksi että mallivastausta saattoi rauhassa kokeilla ilman että plugin lataa vanhemman vastauksen tallentamisen jälkeen. Tämä tosin haittaa tehtävien arvostelua, sillä opettajanäkymässä show valid on oletuksena pois (tai dokumenttiasetuksilla säädetty)
=> Don't force show invalid answers because of modelAnswer in teacher mode

timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/static/scripts/tim/document/editing/editing.ts, timApp/static/scripts/tim/document/viewctrl.ts, timApp/static/scripts/tim/user/settings.component.scss, timApp/static/scripts/tim/user/settings.component.ts, timApp/static/scripts/tim/util/globals.ts, timApp/tests/browser/browsertest.py, timApp/tests/browser/test_questions.py, timApp/tests/server/test_settings.py, timApp/user/preferences.py, timApp/user/settings/settings.py
Use persistent user setting for storing ParMenu position, instead of using browser's LocalStorage.
- resolves #3467 
- adds setting controls under 'Menus' preferences in TIM settings.
- ParMenu function 'Move menu to left/right' now uses the user setting as well
- removes localstorage setting
=> ParMenu location as user setting

timApp/defaultconfig.py, timApp/tim.py
Rajoittaa hakukoneiden indeksointeja TIM-palvelimilla. Asettaa GET-pyyntöjen vastauksiin headerin `X-Robots-Tag` joko globaalisti tai hakukoneittain riippuen `defaultconfig.py`ssä annetuista arvoista (muuttujat `RESTRICT_ROBOTS`, `RESTRICT_ROBOTS_METHODS`).
Katso myös: <https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag#xrobotstag>.
=> Restrict indexing and archiving by search provider crawler bots

timApp/item/manage.py
Estää käsittelemättömän poikkeuksen joka tulee kun yritetään lokittaa oikeuden poistoa oikeudesta joka oli jo poistettu. (esim kaksi muokkaajaa poistelee oikeuksia samaan aikaan)
Lisäksi viilaus sille ettei olemattomia käyttäjäryhmiä lokiteta onnistuneeksi ryhmälisäykseksi. 
https://timdevs01-3.it.jyu.fi/manage/permissions (avaa esim kahteen välilehteen ja poista sama oikeus molemmissa)
=> Check removed permission before logging

timApp/answer/answers.py, timApp/tests/server/test_answers.py, timApp/tests/server/test_hide_names.py, timApp/tests/server/test_teacher.py, timApp/util/answerutil.py
Lisää workaroundin yhteispisteiden laskennalle joissain sivuissa. 
Nykyinen pistetilanteiden hakufunktio `answer.get_users_for_tasks` rakentaa yhden ison SQL-lausekkeen, joka hakee käyttäjien uusimmat vastaukset ja laskee niistä samalla yhteispisteet sekä tehtyjen tehtävien määrän.
SQL-lauseketta rakennettiin joskus silloin, kun datamäärä oli pieni, joten SQL-kyselyä ei silloin ajateltu optimoida, vaan sen sisään on lisätty vaan uusia laskuja. Nykyisellään kyseinen lauseke on niin hidas, että joissain dokumenteissa teacher-tilan lataamisessa voi mennä yli 30 sekuntia.
Tämä PR lisää (toivottavasti) väliaikaisen workaroundin, joka pilkkoo SQL-lausekkeen kolmeen osaan ja siirtää kaikki laskut Pythonin puolelle. Muutoksen ansiosta käsittelyaika putoaa muutamaan sekuntiin.
Esimerkki:
- …
=> Add workaround for answer fetching performance

timApp/document/docparagraph.py
https://tim.jyu.fi/view/users/sijualle/kokeiluja/rndmacro vs https://timdevs01-3.it.jyu.fi/view/rndmacro
Tuohon jää vielä yksi turha päivitetty kappale eli tuo missä käytetään satunnaista makroa ja nocache="true"
=> Re-check changed pars after sanitizing

typos.toml
Revision hashes are a constant source for false positives, so exclude database migration files from typos check when running CI on PRs/pushes.
=> Exclude db migrations from ci-typos checks

timApp/document/docsettings.py, timApp/document/macroinfo.py, timApp/printing/documentprinter.py, timApp/tests/server/test_macros.py, timApp/util/get_fields.py
Closes #3525 
Testisivu: <https://timdevs01-5.it.jyu.fi/view/users/test-user-1/test-fieldmacros> (testuser1)
The new `fieldmacros` setting allows to fetch user's current field values into macros. The syntax is the same as for JSRunner fields; that is:
```
fieldmacros:
- field1
- field1.points=f1p
```
and this approach supports the same field types (i.e. tallies, plugininfos, etc.).
At the moment, all user's fields can be used in fieldmacros, but only user's own latest valid answer is displayed. This means that a user can fetch their own answers from any document (just as they can do so by requesting the full personal GDPR-compliant data dump from TIM).
The setting displays fields only for the current user and does not switch the values in teacher mode. This will probably be an impossible …
=> docsettings: Add fieldmacros option

timApp/answer/answers.py, timApp/answer/routes.py, timApp/plugin/jsrunner/util.py, timApp/tests/server/test_answers.py, tim_common/markupmodels.py
Esimerkki: <https://timdevs01-5.it.jyu.fi/view/users/test-user-1/test-single-save> (testuser1)
The `saveSingleAnswer` plugin option allows to only store the latest save attempt for each user. If the user sends multiple answers for the plugin task, only the latest answer will be saved.
The option is primarily intended for use with automatically computed fields (e.g. learning analytics dashboards in courses or progress markers for use with `fieldmacros`). For such cases, storing only a single answer per user will reduce database usage and keep page loading performance the same over time.
The option can be used with any plugin, but the UI currently may not properly support it.
=> plugin: Add saveSingleAnswer option

timApp/admin/routes.py, timApp/auth/login.py, timApp/auth/sessioninfo.py, timApp/document/docviewparams.py, timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/item/routes.py, timApp/static/scripts/tim/user/user-menu.component.ts, timApp/static/scripts/tim/user/userService.ts, timApp/static/scripts/tim/util/globals.ts, timApp/templates/base.jinja2
Closes #3515 
Testaus: <https://timdevs02.it.jyu.fi/> (testaa omalla admin-tunnuksella)
Helpottaa admin-tunnuksella käyttäjätunnuksen vaihtamista ja palauttamista. Toteuttaa kolme uutta ominaisuutta:
1. Quick Login GUI
Adminille näkyy nyt ylävalikossa "Admin: Vaihda käyttäjä" -painike:
Tämä avaa yksinkertaisen dialogin, jolla voi hakea ja nopeasti kirjautua sisään toisena käyttäjänä.
2. Lisätty "Vaihda käyttäjään" -painike, kun on Quick Login päällä.
Kun on kirjautunut toisella käyttäjällä quick loginissa, ylävalikossa näkyy uloskirjautumisen sijaan "Vaihda käyttäjä" -painike:
Painikkeella voi palata takaisin omaksi käyttäjäksi ilman sitä, että tarvitsee kirjautua kokonaan ulos.
3. Lisätty `as_user=` URL-parametri
Kyseisellä URL-parametrilla voi esikatsella yksittäistä sivua jollain …
=> Simplify admin quick login GUI

timApp/answer/routes.py, timApp/plugin/jsrunner/jsrunner.py, timApp/plugin/jsrunner/util.py
Tämä kortti on osana kurssin "Julkisten hankintojen perusteet" tarvittavia ominaisuuksia.
Adds JSRunner option to allow overwriting validity state of current answers. This allows to, for example, unlock/lock tasks with more ease.
Testi:
- <https://timdevs01-5.it.jyu.fi/view/users/test-user-1/test-invalid-reset>
=> jsrunner: Add canOverwriteValidity option

timApp/modules/jsrunner/client/javascripts/jsrunner-plugin.component.ts, timApp/modules/jsrunner/shared/jsrunnertypes.ts, timApp/modules/svn/js/video.component.ts, timApp/static/scripts/tim/document/viewctrl.ts
Toteutetaan ominaisuuksia, joita tarvitaan kurssille "Julkisten hankintojen perusteet":
- Videoiden loppuessa voi suorittaa JSRunner
- JSRunnerilla on mahdollisuus virkistää sivu ajon lopuksi
- Lisäksi virkistyessä voidaan ajaa toinen JSRunner
- Pieni ominaisuus: JSRunnereiden alueiden piilotusta/näyttämistä voi tehdä nyt väliaikaisesti ilman, että tila tallentuisi localStorageen
Testit/esimerkit:
- JSRunnerin ajaminen videon loppuessa: <https://timdevs01-5.it.jyu.fi/view/users/test-user-1/test-video-jsrunner>
- JSRunner ja sivujen virkistäminen: <https://timdevs01-5.it.jyu.fi/view/users/test-user-1/test-jsrunner-refresh>
=> Add integration between videos and JSRunner, add refresh support for JSRunner

timApp/lecture/question_utils.py, timApp/plugin/qst/qst.py
Pakottaa qst-tehtävissä expl-attribuutin dictiksi/tyhjäksi/puuttuvaksi
Noissa satunnaistusfunktioissa oletetaan että expl joko puuttuu tai on objekti. Tuosta on tullut jonkin verran wuffeja jos se on ollut esim pelkkä merkkijono ja satunnaistus on ollut käytössä
Laitoin haaran devs02:een timdevs02.it.jyu.fi
Nopeasti testattuna nykyiset qst-tehtävät ja luentokysymykset toimii. Koitin haulla katsoa onko jossain aktiivisessa dokumentissa käytetty väärää muotoa, mutta niitä ei näyttänyt olevan
=> Qst: enforce expl as dict or None

timApp/notification/group_notification.py, timApp/sisu/scim.py, timApp/static/tim_docs/initial/group_preamble.md, timApp/tests/server/test_groups.py, timApp/user/user.py
Esimerkki: <https://timdevs01-5.it.jyu.fi/view/groups/testgroup1>
- testuser1 omistaa ryhmän
- Huom: Testiä varten kannattaa tehdä oma tunnus toimivalla sähköpostilla, niin voi kokeilla viestin saapumista
This feature allows to set an automatic welcome message to be sent to the users that are added to a user group. To specify the message, save it as a global answer to the user group management document with task name "GLO_join_message". The contents of this global answer are used as the message contents.
=> Add ability to send welcome message to new group users

timApp/plugin/plugin.py
This adds InlinePluginFinder class that allows to find inline plugins in a document. Additionally, this adds a cached version, CachedInlinePluginFinder. The cached version is able to cache results, speeding up finding inline plugins in a document.
Käyttötapaus erityisesti SUKOLin varauslomakkeessa.
Tuotanto: <https://tim.jyu.fi/view/sukol/hallinto/2024/kokeenvaraus>  
Tämä PR: <https://timdevs01-5.it.jyu.fi/view/users/dz-dz/test-sukol>  (mikä tahansa testuser)
=> Add InlinePluginFinder and cached version

timApp/modules/cs/js/util/util.ts
Ignore solitary punctuation characters in input, since some languages' syntax dictates whitespace before e.g. exclamation/question marks etc.
=> Fix word count for csplugin textarea (via countboard component)

timApp/admin/translationservice_cli.py, timApp/defaultconfig.py, timApp/document/translation/deepl.py, timApp/document/translation/routes.py, timApp/document/translation/translator.py, timApp/tests/server/timroutetest.py
Fixes an issue with translation source document always being the original 'parent' document, even when initiating the translation process from an existing translation.
Translation source will now be the currently open document, when creating a new translation from its Manage-page. Paragraph references will still point to the original.
TODO
<s>- [ ] Reference paragraph ids when matching paragraphs to enable partial translations (when creating a new translation from an existing, partial translation, for example)</s> (Move to its own PR/issue, if this does not turn out to be critical)
After merging, run the following:
1. `./tim run flask language update`
2. `./tim run flask trservice purge-deepl-lang-cache`
The latter clears the memoized cache for supported language pairings, since the …
=> Fix translation source

timApp/plugin/plugin.py, timApp/static/scripts/tim/document/editing/editing.ts, timApp/tests/server/test_editing.py
Mahdollistaa drawio-editorin käytön suoraan käännetyssä dokumentissa
https://timdevs01-3.it.jyu.fi/view/drawiokaannos/en-GB
=> Edit Drawio in translated documents

timApp/answer/routes.py, timApp/modules/jsrunner/server/routes/answer.ts, timApp/modules/jsrunner/server/routes/tools.ts, timApp/modules/jsrunner/shared/jsrunnertypes.ts, timApp/plugin/jsrunner/jsrunner.py, timApp/plugin/jsrunner/util.py, timApp/sisu/sisu.py, timApp/tests/server/test_scim.py
Testi: <https://timdevs02.it.jyu.fi/view/users/dezhidki/test-s2s-jsrunner> (testaa omalla tuotannon admin-tunnuksella)
Adds a JSRunner function `gtools.sendGradesToSisu(opts)` function. When called, the function triggers sending students' grades to Sisu after the script finishes executing.
To send grades to Sisu, the following must apply:
- destCourse must be set in the JSRunner's markup
- The student must have a value in the `grade` (course grade) field.
- The student must have a value in the `credit` (course credits) field.
- The student must have a value in the `completionDate` (course completion date) field.
By default, grades for all students specified in the `group` markup field will be sent to Sisu. If `group` is the wildcard "*", then the `group` option in the document settings …
=> jsrunner: Add gtools.sendGradesToSisu

cli/commands/i18n/extract.py, cli/commands/i18n/init_lang.py, cli/docker/run.py, cli/util/proc.py
Lisää CLI-komennon, jonka avulla on helpompi alustaa Babelin käännöskatalogi uusille kielille.
Käyttö: `./tim i18n init-lang <kielikoodi>`
Kielikoodi annettava Babelin tukemassa muodossa (ISO 639-3 ja BCP 47, kts. https://cldr.unicode.org/index/cldr-spec/picking-the-right-language-code).
=> CLI: Add cli command to init babel translation catalogs

timApp/static/scripts/tim/velp/reviewController.ts
Avaa velpit marginaaliissa jos plugin ei palauta kunnollista reviewhtml:ää (esim mcq)
https://timdevs01-3.it.jyu.fi/teacher/mcqvelps
=> Velps: fall back to InMarginOnly if reviehtml fails to load

timApp/static/scripts/tim/document/areas.ts
Elements marked with the class `.no-areaexpand` will not trigger area expansion / collapse when clicked.
TODO:
- some complex elements need to be defined in code currently, need a better way to handle them
=> No area expand/collapse trigger for marked elements

timApp/defaultconfig.py, timApp/document/translation/deepl.py, timApp/document/translation/reversingtranslator.py, timApp/document/translation/routes.py, timApp/document/translation/translator.py, tim_common/vendor/requests_futures.py
Alleviates translation errors resulting from too many requests being sent to the translation service url.
Adds optional arguments `max_workers` and `max_retries` that are passed to the FuturesSession objects performing the translation requests. Both can be controlled in `defaultconfig.py` via the variable `TRANSLATION_SESSION_OPTIONS`.
`max_workers` defaults to 8 (FuturesSession default, moved to `requests_futures.DEFAULT_MAX_WORKERS`) if not set.
`max_retries` defaults to `requests.adapter.DEFAULT_RETRIES`, which should be 0.
Current proposed default is 4 for both, which is set in `defaultconfig.py` by this PR.
=> Add optional arguments for translation sessions

timApp/static/scripts/tim/editor/AceParEditor.ts
Closes #3560
Modifies the custom keymapping for inline comment block `{!!! !!!}`
from `CTRL+Y`/`CMD+Y` to `CTRL+SHIFT+K` to avoid conflicts with
[Windows](https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec), [macOS](https://support.apple.com/en-us/HT201236) and [ACE editor default](https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts) keyboard shortcuts.
The new shortcut only conflicts with ACE's mapping for the 'Find previous' search function, which does not seem very essential given that it is also provided in the editor's search UI.
=> Inline comment block shortcut

timApp/plugin/quantum_circuit/quantumCircuit.py, timApp/static/scripts/tim/plugin/quantumcircuit/quantum-circuit.component.ts
Latex lazynä ladattuna menee pluginin ulkopuolelle niin lisätään luokka ja sitten voi kurssin css:ssä siistiä sen.
math_type: svg
css: |!!
.panel-body .stem {
word-break: break-word;
max-height: 50px;
overflow-y: hidden;
}
!!
``````
``` {#tehtava1 plugin="quantumCircuit" .tehtava}
header: "Tehtävä"
stem: |!!
md: Tee sellainen piiri, joka vastaa matriisimerkintää $(I \otimes B)(A\otimes C)$.
!!
nQubits: 3
nMoments: 4
simulate: browser
lazy: true
```
``````
=> quantum: add stem classes

timApp/answer/answers.py, timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/static/scripts/tim/answer/all-answers-dialog.component.scss, timApp/static/scripts/tim/answer/all-answers-dialog.component.ts, timApp/tests/server/test_plugins.py
Adds two sort options, `date` and `date_desc` to `allAnswersPlain` route. These allow sorting the fetched answers by submission time in either ascending (oldest first, `sort=date`) or descending (newest first, `sort=date_desc`) order.
Enables answer sorting for single tasks in the UI and changes the sort priority selection to a dropdown to better accommodate the larger number of sorting options.
=> Add sort options for sorting by answer submit date

timApp/item/manage.py
Remove unused route parameter `complete_history` that was not removed along other changes in original PR.
=> Fix complete history route

timApp/modules/drag/client/drag.ts, timApp/static/scripts/tim/answer/answer-browser.component.ts, timApp/static/scripts/tim/document/viewctrl.ts, timApp/static/templates/answerBrowser.html, timApp/tests/browser/browsertest.py, timApp/tests/browser/test_answerbrowser.py, timApp/tests/browser/test_fields.py
Poistaa poikkeuksen joka heitetään jos /getAnswers-reitti epäonnistuu, mutta ei silti tyhjennä pluginin tilaa kun verkkoyhteys palaa
https://timdevs01-3.it.jyu.fi/view/csplug
Koitin aluksi tehdä tuota niin että taskInfo ladattaisiin ennen getAnswers-kutsuja, mutta käytännössä tuosta tuli paljon ongelmia muihin answerbrowserin osiin ja lopuksi joutui purkalla korjaamaan useampaa kohtaa (vrt https://github.com/TIM-JYU/TIM/compare/master...ab-no-state-clear). Tuo canSafelyChangeState-tarkistus, jota Denis käytti tuossa wip-haarassa toimii paljon yksinkertaisemmin
=> AnswerBrowser: Don't overwrite unsaved states on network errors

timApp/defaultconfig.py, timApp/item/distribute_rights.py, timApp/plugin/userselect/dist_right_util.py, timApp/plugin/userselect/userselect.py, timApp/tim_celery.py
(Aikatestit ja esimerkit alla)
Fixes #3423
This commit adds support for distributing rights using all available machines to improve distribution times.
The commit adds a new configuration option DIST_RIGHTS_NETWORK that allows to specify right distribution hosts and network as follows:
```py
{
"hosts": {
"machine1": "https://machine1.tim.education",
"machine2": "https://machine2.tim.education",
"machine3": "https://machine3.tim.education",
"machine4": "https://machine4.tim.education",
},
"distribute_groups": {
"group1": [
"machine1",
"machine2"
],
"group2": [
"machine3",
"machine4",
],
},
"distribute_targets": {
"target1": [
{ "target": "machine1", "distribute_group": "group1"},
{ "target": "machine3", "distribute_group": "group2"},
],
},
}
```
Further, UserSelect now supports two new …
=> distribute_rights: Add relayed right distribution

timApp/admin/routes.py, timApp/document/caching.py, timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/item/routes.py, timApp/static/scripts/tim/document/IDocSettings.ts, timApp/static/scripts/tim/document/viewctrl.ts, timApp/static/scripts/tim/messaging/tim-message-view.component.ts, timApp/static/scripts/tim/messaging/tim-message.component.ts, timApp/static/scripts/tim/ui/goto-link.component.ts, timApp/static/scripts/tim/ui/time-left.component.ts
Testi: <https://timdevs01-4.it.jyu.fi/view/users/admin-admin/test-polling>
Testatut tapaukset:
- Oikeuden kesto vaihdetaan => uusi Time left -aika päivittyy käyttäjälle automaattisesti
- Käyttäjälle asetetaan veisti => viesti tulee näkyviin ja peittää sivun
- Käyttäjälle asetetaan toinen viesti toisen viestin ollessa näkyvissä => vanhan viestin tilalle tulee uusi viesti
- Käyttäjältä otetaan viesti pois => viesti poistuu
- Käyttäjä menee toiseen dokumenttiin viestin kanssa => viesti näkyy toisellakin sivulla
- Nopeustesti => pollauspolun kesto 33 ms
- Kuormatesti => pollauspolku vain lukee data, joten ei lukitusta, mikä voisi timeoutata
- Muita testitapauksia, joita pitäisi testata?
This commit allows polling for document view info route via a document setting:
```yml …
```
=> document: Add pollDocumentViewInfo and global messages

timApp/modules/cs/js/csPlugin.ts
Korjaa cspluginin toimintaa niin, että cspluginissa olevasta countboard-komponentista välittyy sen preventSave-attribuutin arvo cspluginille. Tämä mahdollistaa sen, että cspluginiin annettavan vastauksen pituutta pystyy oikeasti rajoittamaan, eli sen avulla voi estää liian lyhyen/pitkän vastauksen tallentamisen.
Liittyy:  #2605 
TODO:
- estetty funktiossa `runCodeCommon`, estämällä `doRunCode`n ajaminen jos `preventSave == true`
- tämä vaatinee vielä tarkempaa tutkimista: 
- onko tapauksia, joissa halutaan ajaa doRunCode, mutta ilman että vastaus tallennetaan?
- esim. halutaan että tehtävä estää liian lyhyen/pitkän koodin tallentaminen, mutta pitäisi pystyä testaamaan/ajamaan koodi silti?
Rajoituksena toistaiseksi myös, että cspluginin pitää olla tekstityyppinen (text, css, md) …
=> csplugin: Fix preventSave attribute

timApp/admin/item_cli.py
Adds a CLI command to permanently delete TIM documents and folders, including:
- database entries
- disk files
TODO:
- remove resources and entries directly attahed to the document (velps, document comments, etc.)
- plan for dealing with backups
Closes #3670
=> CLI command to permanently delete docs and folders

timApp/answer/routes.py, timApp/static/scripts/tim/answer/answer-browser.component.ts, timApp/tests/browser/test_translation.py, timApp/tests/server/test_plugins.py
Poistaa doc_id ja par_id -parametrit getState-kutsuista.
Tällä hetkellä doc_id:tä ei käytetä ollenkaan, par_id:tä käytetään jonkinlaisena saniteettitarkistuksena joka ei kuitenkaan erikoistilanteissa mene läpi (#3658)
Nykyään getStatessa plugin haetaan suoraan pyynnössä taskId:llä tai kaivetaan vastausid:stä taskId. Käännöksiä varten on erikseen ref_from_doc_id/ref_from_par_id. Tuo vanha par_id on ollut joskus oleellinen kun ei käytetty taskId:tä:
https://github.com/TIM-JYU/TIM/blob/4cbed36653331470b2ffec7a20c6a783cb57d81b/timApp/answer/routes.py#L465
https://tim.jyu.fi/teacher/users/sijualle/kokeiluja/blockidbugi/dest/en vs https://timdevs02.it.jyu.fi/teacher/users/sijualle/kokeiluja/blockidbugi/dest/en
=> Remove doc_id and par_id from /getState

timApp/static/scripts/tim/timRoot.ts, timApp/util/flask/search.py
Block anonymous (ie. not logged-in) users from performing searches.
=> Fix: disallow using search functionality when not logged in

timApp/modules/cs/templates/2/5
Päivittää TIMin ParEditorin menussa olevan QR-koodigeneraattorin (Plugins -> Others -> QR code) käyttämään Googlen toimimattoman palvelun sijaan LaTeX:ia/tikz:ia.
Oletuksena QR-koodiin tulee osoite `https://tim.jyu.fi/lecture/"~docid~"?lecture=autojoin`, mutta tätä voi muokata suoraan editorissa.
=> Update QR code generation option in TIM editor menu

timApp/static/scripts/tim/document/structure/parContext.ts
ParContext.getContent() may return null when called by ParContext.textContent(). If it is null, we will just return an empty string instead:
https://github.com/TIM-JYU/TIM/blob/437f9a6d41aca01b6bd26298d46e1c9fffdca80e/timApp/static/scripts/tim/document/readings.ts#L155-L159
=> Fix null reference in textContent()

timApp/static/scripts/tim/header/header.component.ts
If the current document request contained url parameters, they are added to the document's translation link buttons in the page's header bar. This improves navigability between translations when documents employ url params to set macro/variable values.
=> Add current URL params to translation link buttons in the header bar

timApp/idesupport/utils.py, timApp/upload/upload.py
Adds possibility to define extra files for IDE task downloads.
Example usage:
`````yaml
``` {#lentokone plugin="csPlugin" ideTask="lentsikka-tehtävä" id="kBaKtXsqMJ8X"}
filename: exercise.py
type: py
path: user
fullprogram: |!!
!!
ide_extra_files:
- content: |
def for_local_testing():
filename: extra_file.py
- source: /files/41/file_in_tim.py
filename: file_from_tim.py
- source: /images/42/image_in_tim.gif
filename: image_from_tim.gif
- source: "https://url-to-image.jpg"
filename: file_from_url.jpg
```
`````
=> Feature ide extra files

timApp/idesupport/utils.py
Generating supplementary files (.csproj for cs type exercises) feature was disabled in feature-ide-extra-files pull request.  This makes it work again.
=> Fix generating ide supplementary files

timApp/document/translation/deepl.py, timApp/document/translation/routes.py
Requests sent to the DeepL API previously only considered the API limit on text parameters per request. For some documents, translation requests would fail because the enforced text parameter limit still allowed the request size limit to be exceeded.
This PR corrects this issue by limiting the request payload size to within the API limits.
Oversized translation requests will not throw an exception anymore, they are simply ignored so that valid sections of the document are still able to be translated. There is currently no simple way to split the text content of those requests into multiple requests without breaking the document or running into errors.
Caching for `DeeplTranslationService.languages()` has been disabled for now. It seems to cause occasional problems with the returned …
=> Fix sending oversized translation requests

timApp/modules/svn/js/video.component.ts
If `defaultSubtitles` attribute is set on a showVideo plugin, check for the TextTracks `language` property first. This allows us to use the global macro `%%doclang%%` to automatically choose the default subtitle track according to the current document's language.
=> showVideo: support document language code for defaultSubtitles

timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/static/scripts/tim/sidebarmenu/tabs/settings-tab.component.ts, timApp/static/scripts/tim/user/settings.component.ts, timApp/static/scripts/tim/util/globals.ts, timApp/tests/server/test_settings.py, timApp/user/preferences.py, timApp/user/settings/settings.py, timApp/user/settings/style_utils.py
Quick themes are toggle buttons in the Settings tab that allow to quickly enable and disable user themes. The selections are preserved on a per-session basis, allowing to modify which styles to keep enabled for different devices.
For example, the feature can be used to add a toggle button for one's favorite dark theme and have it easily be enabled or disabled for different devices.
=> settings: Add support for quick themes

timApp/static/scripts/tim/sidebarmenu/tabs/settings-tab.component.scss, timApp/static/scripts/tim/sidebarmenu/tabs/settings-tab.component.ts
Set max-width for quick themes container in sidebar menu settings tab, otherwise the tab will grow excessively wide if a user has a large amount of quick themes set (or the quick themes have very long names).
Also adjusts the `Manage scheduled functions` button style to be be consistent with other buttons on the settings tab.
=> Set max-width for quick themes container

timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/static/scripts/tim/header/site-header.component.ts, timApp/static/scripts/tim/user/settings.component.ts, timApp/static/scripts/tim/util/globals.ts, timApp/tests/server/test_settings.py, timApp/user/preferences.py
Adds a user setting to control header menu default visibility. Document settings still override the user setting.
=> Add user setting for header menu (navbar) visibility

timApp/modules/cs/cs.py, timApp/modules/cs/cs_utils.py, timApp/modules/cs/languages.py, tim_common/fileParams.py, tim_common/utils.py
Tarkoituksen oli saada --autoplot -optio, jolla Python ohjelma muuttaa komennon plt.show()
sellaiseksi että se tallentuu tiedostoon ja se nostetaan clientille.  Eli tavoite oli että
sama ohjelma toimii headless ja näytön kanssa.
En tiedä kuinka sekaisin meni, kun se pycharmin vaihto jotenkin sotki koko jutun ja vaihdon jälkeen koodasinkin
huomaamatta master-haarassa (joka on nyt mulla ihan sekaisin)
Isoimmat muutokset tein languages.py kohtaan PY3
Sitten jonkin verran muuttelin attribuutteja cs.py.  Loput muutokset on vain koodin
siirtämistä metodeiksi cs/cs_utils.py ja tim_common/utils.py tiedostoissa.
Pari alustusta tuli fileparams.py.
commit oli 6918ace5a
=> Python auto plot

timApp/static/scripts/tim/answer/answer-browser.component.ts
Currently, keyboard shortcuts in the AnswerBrowser component interfere with standard, built-in keyboard controls for textfields and textareas, mainly
- `CTRL + left arrow` and
- `CTRL + right arrow`,
which are normally used to move the cursor left and right a whole word at a time when navigating (editable) text content.
This behaviour in the answerbrowser results in frequent disruptions, for example, when adding annotations to students' answers and subsequently adding comments to those annotations: since the answerbrowser hijacks the keyboard event from the textfield, trying to navigate the comment text while editing it via the `CTRL + left/right arrow` results in changing the active answer.
This PR corrects this behaviour by adding the `ALT` modifier key to the conflicting AnswerBrowser …
=> Fix Answerbrowser shortcuts

.github/workflows/lint.yml, timApp/document/docsettings.py, timApp/modules/feedback/js/feedback.ts, timApp/static/scripts/tim/plugin/tim-menu/tim-menu-plugin.component.ts, timApp/static/scripts/tim/ui/draggable.ts, timApp/static/scripts/tim/user/userService.ts, timApp/static/scripts/tim/velp/reviewController.ts
Comments out some console logging that had, apparently, been used for debugging.
Console logging is still being used in some older components, see:
[log(string) from utils.ts](https://github.com/TIM-JYU/TIM/blob/cd708cc8093a1086194f7295b0aec1030dcecb56/timApp/static/scripts/tim/util/utils.ts#L852-L854)
[feedback.ts](https://github.com/TIM-JYU/TIM/blob/cd708cc8093a1086194f7295b0aec1030dcecb56/timApp/modules/feedback/js/feedback.ts#L1061)
[reviewController.ts, multiple cases](https://github.com/TIM-JYU/TIM/blob/cd708cc8093a1086194f7295b0aec1030dcecb56/timApp/static/scripts/tim/velp/reviewController.ts#L481)
Also, one print on server side caused many unnecessary logs:
[docsettings.py](https://github.com/TIM-JYU/TIM/pull/3766/files#diff-0820db03e88f58f7acaddf4d8b3fb5313cd5682a24a0ee8e67fd241bf …
=> Disable logging debug information to browser console and server logs

timApp/static/templates/answerBrowser.html
https://timbeta03.tim.education/view/users/test-user-1/datetime vs https://tim.jyu.fi/view/users/sijualle/kokeiluja/datetime
Vaihdoin toistaiseksi vain tuon answerbrowserin, muualla ei käytetä tuota date-pipea ja näytti menevän ajat oikein:
=> AnswerBrowser: use regular year numbering instead of week numbering

timApp/modules/cs/languages.py, timApp/modules/svn/svn3.py, timApp/util/flask/requesthelper.py
Check COMPS to get_from_url so easier to write postprogram libraries for JSFrame-components.
Try to minimize svn3.py and csPlugin.py warnings.
Still one left in svn3.py (I could not correct, code is same on csPlugin):
Expected type '(Any, Any, ThreadedHTTPServer) -> BaseRequestHandler' (matched generic type '(Any, Any, Self) -> 
BaseRequestHandler'), got 'Type[TIMShowFileServer]' instead
5 warning left in cs.py ((could not correct):
- Expected type 'str', got 'list | LiteralString | str' instead
- Expected type 'str', got 'list | LiteralString | str' instead
- Unexpected type(s):(str | list | LiteralString)Possible type(s):(LiteralString)(str)
- Unexpected type(s):(list | LiteralString | str)Possible type(s):(LiteralString)(str)
- Expected type 'dict', got 'dict[str, str | Any]' instead …
=> remove minor warnings and add COMPS to get_from_url

timApp/static/stylesheets/stylesheet.scss
Korjaa editorin esikatselu- ja diff-näkymien koon muuttamisen kun kys. näkymät ovat 'irrotetussa' tilassa (detached).
Aikaisemmin irrotetuilla ikkunoilla oli asetettuna enimmäiskoko, mikä rajoitetti niiden koon varsin pieneksi. Tämän PR:n jälkeen irottettuja ikkunoita voi hyödyntää paljon paremmin erityisesti dokumenttien käännöksiä editoidessa.
=> Fix resizing detached preview windows in editor

timApp/tests/server/test_url_redirect.py, timApp/tim.py
This commit strengthens cleaning of double slashes in URL paths to prevent a potential open redirect exploit via abuse of whitespace.
***
Tämänhetkinen `//`-merkkijonojen siivous polusta mahdollistaa käyttäjästä riippumattoman ja odottamattoman redirectin, ks. esim <https://tim.jyu.fi/%09/example.com/>. 
Tämä on tunnettu bugi, katso esim. <https://github.com/oauth2-proxy/oauth2-proxy/security/advisories/GHSA-j7px-6hwj-hpjg>
PR vahvistaa `//`-merkkijonojen siivouksen siivoamalla kaikki välilyöntimerkit pois. Mukana yksikkötestit, jotka todentavat korjauksen toimivuuden (korjauksen jälkeen `https://tim.jyu.fi/%09/example.com/` ohjautuu `https://tim.jyu.fi/example.com/` joka ei ole validi polku).
=> tim: strengthen double slash cleaning logic

timApp/defaultconfig.py, timApp/tim.py, timApp/user/settings/settings.py, timApp/util/locale.py
Due to changes in how Chrome handles third-party cookies, this commit makes session cookie a first-party cookie by setting SameSite=Lax. This essentially restricts the use of the cookie within the TIM website.
***
Chrome on alkanut varoittaa siitä, että kolmannen osapuolten keksejä (=keksit, joita lähetetään sivulle jonkun ulkopuolisen sivun kautta, [katso MDN](https://developer.mozilla.org/en-US/docs/Web/Privacy/Third-party_cookies)) mahdollisesti estetään ellei niitä konfiguroi oikein. Uusimmilla Chromen versioilla tulee devauskonsoliin seuraavia viestejä:
```
Chrome is moving towards a new experience that allows users to choose to browse without third-party cookies.
``` 
Tällä hetkellä TIMin sessiokekseille asetetaan `SameSite=None`, mikä sallii sessiokeksin lähettämisen mistä tahansa …
=> config: require SameSite=Lax for session cookies

timApp/user/usergroup.py
The property gets a possible human-readable name of the group from the admin doc title if it is available.
---
Tätä asetusta ei vielä käytetä missään, mutta se on edellytys seuraaville PRille.
=> usergroup: Add human_name property

timApp/static/scripts/tim/ui/input-dialog.component.scss, timApp/static/scripts/tim/ui/input-dialog.component.ts
This cleans up and improves the behavior of input dialogs after the recent changes:
- Dialog actions and inputs are disabled while running the async validator
- Reverts `text` to be the default input type instead of textarea (this broke some UI)
- Disables automatic action of the Enter button if the input type is textarea. This prevented multiline inputs before.
---
Näkyvin muutos on inputin korjaus paikoissa, jossa inputin tyyppiä ei ole annettu, esim. "Oma nimi -> Admin: Switch user"
Tuotannossa nyt:
<https://timbeta02.tim.education> (kokeile `testadmin1`/`admin1pass`):
Tämä ilmeisesti on  regressio peräisin jostain OSCAR-commitissa, jossa on lisätty textarea-omana input-tyyppinä ja siitä on tehty oletus.
Lisäksi korjaa vähän tyylivikoja tuotannossa textarea-tyypille (käytetään …
=> InputDialogComponent: Clean up, fix textarea behavior

timApp/plugin/tableform/tableForm.py, timApp/static/scripts/tim/plugin/tableForm/table-form.component.ts, timApp/tests/server/test_tableform.py
Adds support for generating reports in Excel file format (.xlsx) in the TableForm component.
For now, numeric cell values are parsed via regex, string substitutions and type casting, handled cases include
- spaces
- comma (`,`) and dot (`.`) as decimal separators
- multiple commas and/or dots
In the future, the parsing/filtering/type casting mechanism should probably be replaced by something that is configurable from the browser (ie. via the runScripts plugin setting).
=> TableForm: export reports as Excel files

timApp/defaultconfig.py, timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/plugin/tableform/tableForm.py, timApp/static/scripts/tim/plugin/tableForm/table-form.component.scss, timApp/static/scripts/tim/plugin/tableForm/table-form.component.ts, timApp/static/scripts/tim/ui/add-member.component.ts, timApp/static/scripts/tim/util/utils.ts, timApp/tests/server/test_groups.py, timApp/user/groups.py
This change adds a native member creation button to tableForm. Additionally, the button allows creating user accounts for non-existing users and notify them about it.
---
Testisivu: <https://timbeta02.tim.education/view/users/dz-dz/test-adduser-notify-table>
Lisää tableFormiin kolme asetusta:
```yml
addUsersButton: Lisää opettaja hallintaryhmään
notifyOnAdd: true
createMissingUsers: true
```
Sähköpostien sisällöt ovat toistaiseksi muokattavissa vain palvelinasetuksissa, mutta ehkä jatkossa ne voisivat olla kenttiä jossain dokumentissa.
Lisäksi `createMissingUsers` toimii vain, jos palvelinasetus `GROUPS_MISSING_USER_CREATE_ALLOW` on laitettu päälle. Yleisen käytön kannalta voisi miettiä, voisiko tunnusten luominen sallia aina (tai esim. tietylle käyttäjäryhmälle).
=> Feature tableform useradd simple

timApp/static/scripts/tim/velp/reviewController.ts
Adds a `rangeCount` check before calling `Selection.getRangeAt()` in `initVelpSelection`.
Closes #3797
=> Fix: add rangeCount check in initVelpSelection

timApp/static/scripts/tim/answer/answer-browser.component.ts, timApp/static/scripts/tim/plugin/attributes.ts, timApp/static/templates/answerBrowser.html, tim_common/markupmodels.py
Makes the following adjustments to the Points field in the AnswerBrowser component:
- Autosave option: the points value is automatically saved when the field loses focus
- Adjustable with the plugin attribute
```
answerBrowser:
autosave: true / false (default: true)
```
- Limit maximum allowed points for a task answer
- Adjustable with the plugin attribute
```
answerBrowser:
limitPoints:
min: [number]
max: [number]
```
- Hide point field buttons when autosave option is on
Closes #3796
=> Answerbrowser adjustments

timApp/static/scripts/tim/answer/answer-browser.component.ts, timApp/tests/browser/test_answerbrowser.py
Fixes a bug where AnswerBrowser keeps pumping out identical error messages even when the error message already exists.
=> Fix AnswerBrowser error message alerts

timApp/static/scripts/tim/util/math.ts, timApp/static/scripts/tim/velp/annotation.component.ts, timApp/static/scripts/tim/velp/velpWindow.ts, timApp/static/templates/velpWindow.html
Closes #3801 
Relaxes the original constraints placed on changing the color of velps/annotations. Users may now freely choose the color of their velp (templates) and annotations.
The default visibility of annotations is now private (labeled as "Just me" in the annotation) when the user/annotator does not have at least teacher rights to the document. Users with at least teacher rights to the document will continue to have their annotations visible publicly by default.
=> Fix velp color controls

timApp/static/scripts/tim/document/viewctrl.ts
Adds simple keyboard shortcuts handling to ViewCtrl and adds the shortcut **CTRL+E** for opening the paragraph editor on the focused/active paragraph.
Related issues:
- #3795
=> Accessibility: add keyboard shortcut for paragraph editor

timApp/plugin/tableform/tableForm.py, timApp/static/scripts/tim/plugin/tableForm/table-form.component.ts
Testisivu: <https://timbeta01.tim.education/view/users/dz-dz/test-add-jsrunner> (kokeile testuser1)
Kaksi muutosta:
- Lisätty `runScripts.onMemberAdd`-asetus TableFormsiin. Sen avulla skripti voidaan ajaa heti sen jälkeen, kun ryhmään on lisätty uusi käyttäjä. Käyttötarkoituksena on esim. fieldien arvojen asettaminen heti, kun käyttäjä luodaan.
- Jos `runScripts.button` on tyhjä tai null, sitä vastaavaa painiketta ei näytetä tableFormin kohdalla
Näiden avulla on mahdollista toteuttaa loputkin SUKOL-koehallintasivun opettajataulukkoon tarvittavia ominaisuuksia.
=> TableForm: Allow running JSRunners after adding a new user

timApp/answer/routes.py, timApp/defaultconfig.py, timApp/modules/cs/js/csPlugin.ts, timApp/modules/fields/js/dropdown-plugin.component.ts, timApp/modules/fields/js/multisave.ts, timApp/modules/fields/js/textfield-plugin.component.ts, timApp/modules/fields/multisave.py, timApp/static/scripts/tim/plugin/qst/qst.component.ts
- Qst/Dropdown/Csplugin: Estä vastaaminen jos readonly: true
- Multisave: lisää attribuutteja automaattisen tallentamisen ja tallennusvirheiden näyttämisen tueksi
- timer: Automaattinen tallennus x millisekunnin välein
- saveDelay: ms odotus kahden eri tehtävän tallentamisen välillä
- showMessages: Jos true niin kerää ja näyttää virheviestit plugineilta joita yritettiin tallentaa. Toistaiseksi vaan raaka divlista jokaisesta uniikista viestistä
- messageOverrides: lista `{excpect: str/regex, override: str}` jolla voi ylikirjoittaa tallennettavien plugineiden virheviestejä
- conf ANSWER_LOG_FILE: tallentaa raakatiedon vastauspyynnöistä ennen oikeustarkistuksia/pluginkutsuja tms vastauskäsittelyjä
=> Improve multisave automatic saving, check readonly attributes, log answer requests

timApp/idesupport/utils.py
The TIDE-CLI support function `get_ide_user_plugin_data` previously returned the raw value for the `csPlugin` attribute `maxPoints`. However, `maxPoints` is of type `str | int | float | None`, so we cannot use it directly.
This PR rectifies this by calling the task plugin's `max_points()` method, which parses the value of `maxPoints`.
Closes #3812
=> Fix getting max_points value for TIDEPluginData

timApp/idesupport/utils.py
Adds support for the task deadline and answerlimit plugin attributes. TIDE-CLI can then be used to relay deadline and answerlimit information to IDE plugins.
Closes #3817 and #3813
=> Deadline, answerlimit support for TIDE-CLI

timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/migrations/versions/eccae2b73601_add_notificationtypes_for_annotations.py, timApp/notification/notification.py, timApp/notification/notify.py, timApp/notification/pending_notification.py, timApp/static/scripts/tim/item/manage/notification-options.component.ts, timApp/static/scripts/tim/user/settings.component.ts, timApp/static/scripts/tim/util/globals.ts, timApp/tests/db/test_notify.py, timApp/tests/server/test_comments.py, timApp/tests/server/test_manage.py, timApp/tests/server/test_notify.py, timApp/tests/server/timroutetest.py, timApp/tim_app.py, timApp/user/user.py, timApp/velp/annotation.py
Adds subcribable email notifications for annotations ("velps") placed in documents. 
Only publicly viewable annotations will trigger notifications. Answer review annotations do not trigger notifications.
TODO:
See also #406.
Closes #998.
=> Feature: velp notifications

timApp/static/scripts/tim/messaging/manage/message-list-manage.module.ts
`message-list-manage.module.ts` was missing an import for `NoopAnimationsModule`, which prevented sending a TIM message to a group email list.
Closes #3828
=> Fix sending group message as TIM message

timApp/static/scripts/tim/ui/draggable.ts
When slidePars is enabled, move the window to top-left by default. This ensures the window occupies the free space created by the paragraphs that were moved to the right.
---
Jos `float_slide_pars`-lohkoasetus on `true`, tämä PR pakottaa kellutettavan ikkunan oletuksella vasempaan ylänurkkaan.
Tämä PR muuta muuta logiikkaa, sillä kellutettavien lohkoissa käytetään vanhaa Angular.JS:ää. 
Tämän muutoksen pitäisi olla sopivan riittävä mm. SUKOL-kokeisiin.
Testi: <https://tim03.it.jyu.fi/view/sukol/kokeet/2025/a-englanti-2025>  
Tunnuksena toimii oma tuotanto-TIMin tunnus ja salasana. Kyseisellä koneella on kopioa tuotannosta, joten siellä voi testailla myös muita dokumentteja. Omien testien perusteella tämä muuttaa vain niitä lohkoja, jossa on `float_slide_pars="true"`.
=> timDraggableFixed: change default position when slidePars is enabled

timApp/plugin/quantum_circuit/quantumCircuit.py, timApp/static/scripts/tim/plugin/quantumcircuit/gate.service.ts, timApp/static/scripts/tim/plugin/quantumcircuit/quantum-board.ts, timApp/static/scripts/tim/plugin/quantumcircuit/quantum-circuit-board.component.scss, timApp/static/scripts/tim/plugin/quantumcircuit/quantum-circuit.component.ts, timApp/static/scripts/tim/plugin/quantumcircuit/quantum-gate-menu.component.scss, timApp/static/scripts/tim/plugin/quantumcircuit/quantum-gate-menu.component.ts
Kosketuslaitteita varten drag-toiminnon simulointi siten, että kohde liikkuu hieman sormen yläpuolella.
Samoin mahdollisuus estää kontrollipallon poistuminen jos kontrolloitavaksi tulee toinen portti.
Molemmat ominaisuudet optiona, eli sellaisenaan minkään ei pitäisi muuttua vielä
nykyisestä.
removeControls: false     # oletus true jolloin poistaa kontrollipallot kuten nykyisin    
touchOffset: 40               # oletus 0, jolloin ei tehdä touch ollenkaan vaan käytetään selaimen drag
Jos "asiakas" on tyytyväinen muutoksiin, vaihdetaan em. oletuksiksi.
=> Simulated drag to touch devices

timApp/plugin/quantum_circuit/quantumCircuit.py, timApp/static/scripts/tim/plugin/quantumcircuit/gate.service.ts
Includes B and D gates in the basic set of gates, so that they do not always have to be declared in the quantum circuit plugin's markup.
=> Quantum circuit: add B and D as basic gates

timApp/content_report/content_report.py, timApp/defaultconfig.py, timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/static/scripts/tim/footer.component.ts, timApp/static/scripts/tim/ui/report-content-dialog.component.scss, timApp/static/scripts/tim/ui/report-content-dialog.component.ts, timApp/static/scripts/tim/ui/showReportContentDialog.ts, timApp/tim.py
This pull request introduces a content reporting dialog, that is openable from the footer of the TIM UI. 
- User can use the dialog to send the report via email to TIM-administrators, and can optionally add their email address for a followup from the admins.
- New mail address variable is added to default_config.py for the content reports
- Dialog has a button for adding current viewed page address to the report.
- User has an option to autofill their email address to the form.
- Currently translated languages are English and Finnish.
- Success and errors are displayed on the dialog.
TODO:
=> Feature: Report Content Dialog

timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/static/scripts/tim/folder/copy-folder.component.scss, timApp/static/scripts/tim/folder/copy-folder.component.ts
This pull request changes how copy preview items are displayed in the copy-folder component. With this feature, the copy preview is presented in a table, from which items can be manually excluded by checking checkboxes. The items selected manually by the user are passed to the backend as a regular expression containing exact matches to the selected documents or folders.
Additionally, when user checks a parent folder, all the sub items are excluded as well. Currently unchecking an item that is under an excluded parent folder does end up being not copied. This is not necessarily clear from the UI.
There is a checkbox on the top row of the table, that allows user to check and uncheck all of the checkboxes.
Finally, this pull request changes the help text for the input field for the regular …
=> Feature better exclude to copy-folder component

timApp/i18n/messages.fi.xlf, timApp/i18n/messages.sv.xlf, timApp/static/scripts/tim/folder/copy-folder.component.ts, timApp/static/templates/manage.html, tim_common/html_sanitize.py
This pull request adds support for using copy-folder component as a document level element. It can be used as before or using a new feature, where the component can be initialized with copyFrom and copyTo attributes.
Pull request #3867 Makes some translations in this obsolete. 
This pull request aims to solve issue #2497.
TODO:
=> Feature copy folder to documentlevel component

timApp/static/templates/parEditor.html
Previously the 'Import document' tab in ParEditor inherited display:flex for the tab's content, which made the flie browsing button appear in an unexpected location.
Change the import document tab's display prop to inline-block.
=> Fix display prop for 'Import document' tab in ParEditor
