- timApp/answer/routes.py
- timApp/modules/jsrunner/server/routes/answer.ts
- timApp/modules/jsrunner/server/routes/runscript.ts
- timApp/modules/jsrunner/server/routes/tools.ts
- timApp/modules/jsrunner/shared/jsrunnertypes.ts
Lisää `GTools.createUser`-funktio JSRunneriin, jolla voi luoda uusia käyttäjiä. Funktio palauttaa pseudo-ID:n, jonka voi käyttää esim. uuden käyttäjän lisäämiseksi ryhmään samalla.
Toimintahuomioita:
* Käyttäjän lisääminen vaatii, että käyttäjä kuuluu `User creators` -ryhmään (eli on oikeus luoda käyttäjiä).
* Funktiolla ei voi muokata olemassa olevan käyttäjän tietoja. Jos käyttäjä on jo olemassa, uutta ei luoda eikä vanhan tietoja muokata. Tämä niin, koska nimensä mukaisesti `User creators` -ryhmä (joka on jo TIMissa olemassa) ei salli käyttäjätietojen muokkaamista.
* Funktion palauttama ID ei ole todellinen käyttäjäid, vaan JSRunnerin sisäinen pseudo-ID. Tätä IDtä voi käyttää esim. `GTools.addToGroup`-funktiossa, jolloin saman JSRunnerin sisällä käyttäjä voidaan luoda ja lisätä …
> Add GTools.createUser() to JSRunner

- timApp/answer/routes.py
- timApp/i18n/messages.fi.xlf
- timApp/i18n/messages.sv.xlf
- timApp/plugin/pluginControl.py
- timApp/static/scripts/tim/answer/answerbrowser3.ts
- timApp/static/scripts/tim/plugin/attributes.ts
- timApp/static/templates/answerBrowser.html
- tim_common/markupmodels.py
https://timdevs01-3.it.jyu.fi/view/modelanswer2
- modelAnswer-linkkejä ei näy jos vastaus puuttuu, vaikka muut attribuutit olisi paikoillaan (voi määritellä esim pelkät linkTextit globaalisti ilman että mallivastauksettomat pluginit kaatuvat)
- Show valid only oletuksena pois jos mallivastaus
- linkTextCount-attribuutti, jolla voi säätää koska mallivastauslinkki tulee näkyviin
- oletus linktext
> Modelanswer continue

- timApp/static/scripts/tim/answer/answerbrowser3.ts
- timApp/static/templates/answerBrowser.html
https://timdevs01-3.it.jyu.fi/view/modelanswer_tex 
vs
https://tim.jyu.fi/view/hy/kurssit/taloustiede/YET-023a/2022/malli
> Process modelAnswer math

- timApp/item/routes.py
- timApp/templates/base.jinja2
- timApp/templates/partials/doc_head.jinja2
- timApp/user/preferences.py
- tim_common/html_sanitize.py
> Add lxml-based CSS sanitization to personal CSS

- tim_common/markupmodels.py
https://timdevs01-3.it.jyu.fi/view/deadline
> Parse PluginDateTime with isoparse

- timApp/i18n/messages.fi.xlf
- timApp/i18n/messages.sv.xlf
- timApp/package-lock.json
- timApp/package.json
- timApp/static/scripts/tim/answer/answerbrowser3.ts
- timApp/static/scripts/tim/plugin/reviewcanvas.ts
Lisää painikkeen josta voi ladata reviewCanvaksen kuvat yhtenä pdf-pötkönä. Toistaiseksi luodaan kokonaan selaimessa
https://timdevs01-3.it.jyu.fi/teacher/reviewcanvas
> Add option to download reviewCanvas images as PDF

- timApp/answer/routes.py
- timApp/i18n/messages.fi.xlf
- timApp/i18n/messages.sv.xlf
- timApp/plugin/plugin.py
- timApp/static/scripts/tim/answer/pluginLoader.ts
- timApp/static/templates/answerBrowser.html
- timApp/tests/browser/test_model_answer.py
Korjaa answerbrowserin päivityksessä kadonneet mallivastauksen avulla piilotettavat tehtävät + lisää mallivastauksen testit
https://timdevs01-3.it.jyu.fi/view/modelanswer_areahide
vs nykytilanne
https://tim.jyu.fi/view/users/sijualle/kokeiluja/modelanswer_areahide
> Modelanswer tests

- cli/commands/setup.py
- cli/templates/docker/docker-compose.tmpl.yml
- poetry.lock
- pyproject.toml
- timApp/Dockerfile
- timApp/defaultconfig.py
- timApp/item/routes.py
- timApp/proxy/routes.py
- timApp/securitytxt/routes.py
- timApp/testconfig.py
- timApp/tests/server/test_securitytxt.py
- timApp/tim.py
- tim_common/markupmodels.py
Closes #3110 
Lisää GPG-allekirjoitetun [security.txt](https://securitytxt.org/) -tiedoston, jota syksyn pentestaajat yrittivät hakea. Kyseinen tiedosto sisältää meidän yhteystiedot mahdollisia tietoturvailmoituksia varten.
Samalla pieniä refaktorointeja tiedostojen ja polkujen järjestelyyn.
Esimerkki: <https://timdevs01-2.it.jyu.fi/security.txt> ja <https://timdevs01-2.it.jyu.fi/.well-known/security.txt>
> Add security.txt

- timApp/answer/answers.py
- timApp/answer/jsrunner_util.py
- timApp/answer/routes.py
- timApp/auth/accesshelper.py
- timApp/auth/auth_models.py
- timApp/item/manage.py
- timApp/plugin/importdata/importData.py
- timApp/plugin/plugin.py
- timApp/plugin/userselect/userselect.py
- timApp/sisu/sisu.py
- timApp/static/scripts/tim/item/self-expire.component.ts
- timApp/tests/server/test_permissions.py
- timApp/tests/server/test_self_expire.py
- tim_common/html_sanitize.py
Closes #3206
Toteuttaa #3206 sekä testit. Esimerkki: 
* <https://timdevs01-2.it.jyu.fi/view/users/dz-dz/test-self-expire?unlock=true> - koesivu
* <https://timdevs01-2.it.jyu.fi/view/users/dz-dz/test-self-expire-table> - kirjaustaulu
> Self-expire: allow setting fields on expire

- timApp/plugin/plugintype.py
- timApp/plugin/reviewcanvas/reviewcanvas.py
Korjaa tilanteen jossa reviewcanvakselle tuli sisällöksi c tableFormin/jsrunnerin kautta
https://timdevs01-3.it.jyu.fi/teacher/reviewcanvas_null
> Add reviewCanvas to CONTENT_FIELD_NAME_MAP, allow null state

- timApp/document/documentparser.py
- timApp/document/documentwriter.py
- timApp/tests/unit/test_documentparser.py
> Fix code-block rendering

- timApp/defaultconfig.py
- timApp/errorhandlers.py
- timApp/lecture/routes.py
- timApp/tests/server/test_wuff.py
- timApp/tim.py
- timApp/timdb/init.py
- timApp/util/error_handlers.py
- timApp/util/flask/responsehelper.py
- timApp/util/utils.py
Lisää seuraavat asetukset:
* `WUFF_MAX_SAME_COUNT` - kuinka monta samaa virhettä saa tulla ennen kuin se laitetaan mutelle
* `WUFF_MAX_SAME_INTERVAL` - missä ajassa saman virheen pitää tulla, jotta se lasketaan mukaan ylläolevaan asetukseen
* `WUFF_MAX_SAME_MUTE_DURATION` - kuinka pitkäksi virhetyyppi mutetetaan, jos yllä olevan ajan sisään virheitä tulee yli yllä olevan määrän
PR:n tarkoituksena on rajoittaa virhespammi, joka voi tulla esim. Sisulta. Virheet lasketaan tyyppikohtaisesti, eli siis eri tyyppiä oleva virhe ei mene mutelle jonkun toisen virheen takia.
Testi: <https://timdevs01-2.it.jyu.fi/exception> (edellyttää admin-tunnuksen, esim testuser1)
> Add options to mute consecutive wuffs

- timApp/i18n/messages.fi.xlf
- timApp/i18n/messages.sv.xlf
- timApp/plugin/reviewcanvas/reviewcanvas.py
- timApp/static/scripts/tim/plugin/reviewcanvas/review-canvas.component.ts
Muuttaa reviewCanvaksen pdf-linkin sanamuotoilua (Lataa kuvat pdf-tiedostona -> Näytä kuvat pdf-tiedostona), ja lisää attribuutin pdfLinkText jolla voi säätää omat sanamuotoilut tai poistaa linkin kokonaan
https://timdevs01-3.it.jyu.fi/view/reviewcanvas
> Reviewcanvas pdftext

- timApp/i18n/messages.fi.xlf
- timApp/i18n/messages.sv.xlf
- timApp/static/scripts/tim/search/search-box.component.scss
- timApp/static/scripts/tim/search/search-box.component.ts
> Add folder selectors for search; fix relevance typeahead

- timApp/util/flask/search.py
Optimizes database queries when using the search functionality.
> Optimize search database queries

- timApp/i18n/messages.fi.xlf
- timApp/i18n/messages.sv.xlf
- timApp/i18n/xlf-merge.js
- timApp/static/scripts/tim/search/search-box.component.scss
- timApp/static/scripts/tim/search/search-box.component.ts
- timApp/static/scripts/tim/search/search-results-dialog.component.ts
Localizes search functionality and adds a note about browser search shortcut keys.
> Localize search functionality

- timApp/answer/jsrunner_util.py
- timApp/answer/routes.py
- timApp/auth/accesshelper.py
- timApp/document/editing/routes.py
- timApp/item/routes.py
- timApp/peerreview/util/groups.py
- timApp/peerreview/util/peerreview_utils.py
- timApp/static/scripts/tim/document/viewctrl.ts
- timApp/upload/upload.py
- timApp/velp/annotation.py
- timApp/velp/annotations.py
Korjaa `getUpdatedPars`:ssa aiheutuvan wuffin
```
File "/service/timApp/document/post_process.py", line 376, in process_areas
html_par.areainfo.is_collapsed = None
AttributeError: 'NoneType' object has no attribute 'is_collapsed'
```
Ongelma tuli ehdollisesti näkyvistä alueista, jossa ehtona käytettiin esim. `isview`. Polku ei saanut tietoa aktiivisesta näkymästä, joten se ei osannut oikein päätellä lohkojen näkyvyyttä ja tilaa.
Korjauksessa polulle viedään oikea tieto näkymästä (ViewContext). Koska polun palautetut tiedot riippuvat näkymästä, polkuun on samalla lisätty laajennettu oikeustarkistus, joka on refaktoroitu ulos `/view` yms poluista.
Esimerkki: <https://timdevs01-2.it.jyu.fi/teacher/users/dz-dz/test-par-update-ctx>
> Fix getUpdatedPars not receiving view context

- timApp/modules/fields/js/textfield-plugin.component.scss
- timApp/modules/fields/js/textfield-plugin.component.ts
https://timdevs01-3.it.jyu.fi/view/varaus vs https://tim.jyu.fi/view/users/sijualle/kokeiluja/varaus
> Use form-control class in textField textArea

- timApp/upload/upload.py
https://timdevs01-3.it.jyu.fi/view/reviewcanvas
> Warn properly about oversized reviewcanvas uploads

- timApp/answer/routes.py
- timApp/i18n/messages.fi.xlf
- timApp/i18n/messages.sv.xlf
- timApp/static/scripts/tim/answer/answer-browser.component.ts
- timApp/static/scripts/tim/document/interceptor.ts
- timApp/static/scripts/tim/plugin/angular-plugin-base.directive.ts
- timApp/static/scripts/tim/plugin/qst/qst.component.ts
Päivittää pluginin staten aina tallentamisen jälkeen jos postprogramissa on `data.refresh = true`
https://timdevs01-3.it.jyu.fi/view/refresh
> Postprogram refresh

- timApp/static/templates/answerBrowser.html
Lisää luokkia answerbrowserin elementteihin eri css-säätöjä varten
https://timdevs01-3.it.jyu.fi/teacher/ab-minimal
> Add more classes to answerbrowser elements

- timApp/modules/cs/languages.py
https://timdevs01-3.it.jyu.fi/view/csfilter vs https://tim.jyu.fi/view/users/sijualle/kokeiluja/csfilter
> Don't strip out empty lines when checking comtest

- timApp/answer/routes.py
- timApp/static/scripts/tim/answer/all-answers-dialog.component.ts
- timApp/util/flask/responsehelper.py
- Sallii korvikemerkit AllAnswersPlain-reitissä
- Poistaa AllAnswersPlain-reittiin localstoragesta ladattavan groups-urlparametrin jos dokumentin asetuksissa ei ole ryhmiä (eli sillon kuin ui:ssa ei näyt optiota jolla voi säätää pyynnöstä ryhmät päälle tai pois)
https://timdevs01-3.it.jyu.fi/teacher/surrogate
> Allanswers encode

- timApp/i18n/messages.fi.xlf
- timApp/i18n/messages.sv.xlf
- timApp/modules/cs/js/util/file-select.ts
- timApp/static/scripts/tim/plugin/reviewcanvas/review-canvas.component.ts
Lisää reviewCanvakseen kentän johon voi suoraan liittää kuvia liitepöydältä.
https://timdevs01-3.it.jyu.fi/view/rcpaste
> Paste images on reviewcanvas

- timApp/modules/cs/js/csPlugin.ts
Lisää palikkaversion autosavesta cspluginiin (vastaa textfieldiä yms), eli focuksen lähtiessä plugin tallentuu automaattisesti
https://timdevs01-3.it.jyu.fi/view/csautosaves
> Add basic autosave to csPlugin

- timApp/static/scripts/tim/answer/answer-browser.component.ts
https://timdevs01-3.it.jyu.fi/view/qsteen
https://timdevs01-3.it.jyu.fi/view/qsteen/en
> Add reference par info to getModelAnswer

- timApp/defaultconfig.py
- timApp/static/scripts/tim/user/login-dialog.component.ts
- timApp/static/scripts/tim/util/globals.ts
- timApp/templates/base.jinja2
Mahdollistaa omavalintaisen kirjautumisviestin laittamista sisäänkirjautumisdialogiin.
> Add SIMPLE_LOGIN_CUSTOM_LOGIN_MESSAGE

- timApp/modules/cs/Dockerfile
- timApp/modules/cs/dotnet/deps/Directory.Build.props
- timApp/modules/cs/dotnet/deps/nunit_test.csproj
- timApp/modules/cs/dotnet/nunit-test-dll
- timApp/modules/cs/dotnet/runtimeconfig.json
- timApp/modules/cs/dotnet/scripts/cs_test_tester.py
- timApp/modules/cs/languages.py
Päivittää CSPluginin ohjelmointikieliä ja versioita seuraaviin:
* JDK 20.0.1
* JavaFX 20
* .NET 7.0
* NUnit 3.16.3
* Kaikki Python-pakkaukset päivitetty uusimpiin
* Scala 2.13.11
* Swift 5.8.1
* Kotlin 1.8.21
* Rust nightly
* Go 1.20.5
* MongoSH 1.9.1
Samalla pieni Dockerfilen siivous.
Kokeilu: <https://timdevs02.it.jyu.fi> (kirjautuminen omilla tunnuksilla)
> Update CSPlugin languages

- timApp/document/docparagraph.py
> Fix null reference issue with translated preambles

- timApp/static/scripts/tim/downgrade.ts
- timApp/static/scripts/tim/ui/bootstrap-panel.component.ts
- timApp/static/scripts/tim/user/settings.component.ts
- timApp/static/templates/manage.html
Adds heading anchors to the Manage page. Closes #3352.
> UI heading anchors: Manage

- timApp/answer/routes.py
- timApp/static/scripts/tim/answer/answer-browser.component.ts
- timApp/tests/browser/test_model_answer.py
Hakee kaikkien vastausten pisteet tilanteessa jossa pisteitä ei näytetä ennen mallivastauksen avaamista
https://timdevs01-3.it.jyu.fi/view/modelanswer-points
> Query points for all answers with modelAnswer hidePoints

- timApp/i18n/messages.fi.xlf
- timApp/i18n/messages.sv.xlf
- timApp/modules/imagex/imagex.py
- timApp/modules/svn/js/video.component.ts
- timApp/modules/svn/svn3.py
- tim_common/fileParams.py
Lisää pari placeholder-tekstiä laiskoille plugineille (showVideo/image, imagex, cs tiny) tilanteisiin joissa pluginiin ei ole lisätty mitään tekstejä ja lazynä lataamisen vuoksi niiden kohdalle ei tule mitään aktivoitavaa kohtaa
https://timdevs01-3.it.jyu.fi/view/lazyt vs https://tim.jyu.fi/view/users/sijualle/kokeiluja/lazyt
Closes #2163
> Placeholder texts for lazy plugins

- timApp/answer/routes.py
- timApp/i18n/messages.fi.xlf
- timApp/i18n/messages.sv.xlf
- timApp/static/scripts/tim/answer/reset-task-lock-dialog-component.ts
- timApp/static/scripts/tim/answer/reset-task-lock-dialog.component.scss
- timApp/static/scripts/tim/ui/angulardialog/dialog-frame.component.scss
- timApp/static/scripts/tim/ui/input-dialog.component.scss
- timApp/static/scripts/tim/ui/input-dialog.component.ts
- timApp/static/scripts/tim/user/IUser.ts
- timApp/static/stylesheets/style.scss
Lisää paremman UI:n tehtävän mallivastauksen kautta lukinneiden selaamiseen
https://timdevs01-3.it.jyu.fi/view/modelanswer
> Modelanswer lock UI

- timApp/modules/svn/js/video.component.ts
> VideoComponent: Save Adv checkbox state to localStorage

- timApp/static/scripts/tim/plugin/reviewcanvas/review-canvas.component.ts
Näyttää tallennusvirheet reviewcanvaksessa, esim virheellinen postprogram tjsp
https://timdevs01-3.it.jyu.fi/view/reviewcanvas vs https://tim.jyu.fi/view/users/sijualle/kokeiluja/reviewcanvas
> Show errors on successful ReviewCanvas answer

- timApp/document/docviewparams.py
- timApp/i18n/messages.fi.xlf
- timApp/i18n/messages.sv.xlf
- timApp/item/routes.py
- timApp/static/scripts/tim/answer/answer-browser.component.ts
- timApp/tests/browser/test_teacher.py
Lisää user-urlparametrin joka valitsee parametrina annetun käyttäjän kun määritellään kenen vastauksia teacher-näkymässä näytetään sivua avatessa. Tällä hetkellä jos laittaa suoran linkin käyttäjän vastaukseen jota ei ole olemassa, opettajanäkymä saattaa ensin ladata väärän henkilön vastauksen
Lisäksi korjaa bugin joka esti varoitusdialogia näkymästä jos suoralinkistä valittua käyttäjän vastausta ei löytynyt
https://timdevs01-3.it.jyu.fi/view/suoralinkki vs https://tim.jyu.fi/view/users/sijualle/suoralinkki
> User urlparam

- timApp/static/scripts/tim/answer/answer-browser.component.ts
- timApp/static/scripts/tim/plugin/plugin-loader.component.ts
- timApp/static/templates/answerBrowser.html
https://timdevs01-3.it.jyu.fi/view/latexpostprogram vs https://tim.jyu.fi/view/users/sijualle/kokeiluja/postprogramlatex
pitäis ehkä myöhemmin tukea myös math_type: svg
> Fix postprogram math not rendering

- timApp/modules/imagex/imagex.py
- timApp/static/scripts/tim/plugin/imagex/imagex.component.ts
- timApp/static/scripts/tim/plugin/imagex/imagextypes.ts
kolme käyttötapaukseen liittyvää väriasetusta imagex:lle.
https://timdevs01-3.it.jyu.fi/view/lines2
> ImageX: lineColor, correctColor, incorrectColor

- timApp/document/docviewparams.py
- timApp/printing/documentprinter.py
- timApp/printing/print.py
- timApp/tests/server/test_printing.py
Lisää area-urlparametrin (string) toimimaan myös print-reitin kautta, sekä lisää print-reitille "textplain"-parametrin (bool)
https://timdevs01-3.it.jyu.fi/view/video
https://timdevs01-3.it.jyu.fi/print/vtt.vtt?area=1&textplain=true
https://timdevs01-3.it.jyu.fi/print/vtt.vtt?area=2&textplain=true
> Add area and textplain urlparameters to print

- timApp/static/scripts/tim/plugin/quantumcircuit/quantum-circuit.component.ts
quantumCircuit näkymään fieldhelperissä
> Start implementing ITimComponent in quantumCircuit

- timApp/modules/jsrunner/server/routes/answer.ts
- timApp/modules/jsrunner/server/routes/tools.ts
- timApp/modules/jsrunner/shared/jsrunnertypes.ts
- timApp/notification/send_email.py
- timApp/plugin/jsrunner/util.py
- timApp/tests/server/test_jsrunner.py
Testi: <https://timdevs01-5.it.jyu.fi/view/users/dz-dz/test-mail-send> (testuser1 voi lähettää posteja)
The sendMail function allows to send email to users or other email addresses.
Currently, the email sending is only allowed for teachers and admins.
> JSRunner: add gtools.sendMail function

- timApp/item/manage.py
- timApp/item/routes.py
- timApp/static/scripts/tim/app.module.ts
- timApp/static/scripts/tim/document/editing/editing.ts
- timApp/static/scripts/tim/item/create-item-dialog.component.ts
- timApp/static/scripts/tim/item/create-item.component.ts
- timApp/static/scripts/tim/item/showCreateItemDialog.ts
- timApp/static/scripts/tim/ui/tim-utility.module.ts
Lisää create-item-dialog komponentin, jotta create-item komponenttia voi käyttää dialogeissa. Yhtenä käyttötapauksena on TIMin demoaminen, jota varten dialogia voi kutsua suoraan dokumentista painikkesta jolle on annettu luokka .createItem
https://timdevs01-3.it.jyu.fi/view/creator
> Add initial create course button

- timApp/static/scripts/tim/folder/directory-list.component.scss
- timApp/static/scripts/tim/folder/directory-list.component.ts
- timApp/static/scripts/tim/item/create-item.component.ts
https://timdevs01-3.it.jyu.fi/view
> Differentiate folder and document creation visuals

- timApp/static/scripts/tim/editor/AceParEditor.ts
- timApp/static/scripts/tim/editor/BaseParEditor.ts
- timApp/static/scripts/tim/editor/TextAreaParEditor.ts
Lisää rivinvaihdot templateista tulevien pluginlohkojen alkuun/loppuun. https://timdevs01-3.it.jyu.fi/view/asd
=>
> Append newlines to block templates

- timApp/item/routes.py
Pieni muutos kurssidemoreittiin. Jos kansiossa on "index"-niminen tiedosto niin sille tulee päivitetty title, ja jos on preamble niin lisätään menuja varten macro %%homepath%%
https://timdevs01-3.it.jyu.fi/view/users/min-ad/creator
> Update course creator demo

- timApp/document/docinfo.py
- timApp/document/document.py
- timApp/item/manage.py
- timApp/static/scripts/tim/item/manageCtrl.ts
- timApp/static/templates/manage.html
Adds a button to the document version history section that displays the complete document history at once.
> Manage: show complete document history

- timApp/static/scripts/tim/bookmark/bookmark-dialog.component.ts
Korjaa tarkistuslogiikan URL hashien / parametrien checkboxeille kirjanmerkkidialogissa.
> Fix disable checks for checkboxes in add bookmark dialog

- timApp/admin/user_cli.py
Clear password when deleting user.
> Fix deleting account

- timApp/devconfig.py
- timApp/idesupport/utils.py
- Devconfig file fix, now allows to use tide cli when env RUN_IDEPLUGIN_DEV is there
- Logic for exercises, which includes gap in. Validating answer on submission in tide cli
- Refactor for recognizing programming language used in task
> Gap-exercises feature implementation for IDE task

- timApp/redirect/routes.py
- timApp/templates/tim_redirect_error.jinja2
- timApp/tim.py
- timApp/util/error_handlers.py
> first version of redirect

- timApp/static/scripts/tim/messaging/tim-message-send.component.ts
Trigger warning dialog when exiting or reloading page while sending message via TimMessageSendComponent.
Resolves #3702.
> TimMessageSendComponent: Warning on exit

- timApp/modules/cs/cs.py
https://timbeta03.tim.education/view/loop5ever
> Csplugin: Don't give points if program is stuck

- timApp/idesupport/files.py
- timApp/idesupport/ide_languages.py
- timApp/idesupport/routes.py
- timApp/idesupport/utils.py
- timApp/modules/cs/js/csPlugin.ts
- timApp/modules/cs/manager.py
- timApp/modules/cs/ttype.py
- timApp/package-lock.json
- tim_common/cs_utils.py
- Tauno + Jypli works
- automatic Ohjelma.cs and Jypeli project
- if ideTask="" use plugins  #name
- in c# if filename is missing, filename comes from class (todo for java)
- in csplugin.ts use also "--- Write your code below this line. ---" like "BYCODEBEGIN"
- c# project name comes from ideTask 
- implemented by Language-objects, see ide-languages.py (compare languages.py on csPlugin)
> Tide languages

- timApp/i18n/messages.fi.xlf
- timApp/i18n/messages.sv.xlf
- timApp/static/scripts/tim/answer/answer-browser.component.ts
- timApp/static/templates/answerBrowser.html
https://timbeta03.tim.education/view/1csplug
> AnswerBrowser: add refresh button if par has attr ideTask

- timApp/idesupport/ide_languages.py
- timApp/idesupport/routes.py
- timApp/idesupport/utils.py
One .timdata for course => there could be many tasks in same folder (mostly needed by java)
> Feature tide java

- timApp/idesupport/files.py
- timApp/idesupport/ide_languages.py
- timApp/idesupport/utils.py
- timApp/markdown/markdownconverter.py
- timApp/static/scripts/tim/answer/answer-browser.component.ts
- timApp/tests/unit/test_datefilters.py
- task_extra_directory and task_dircetory also to extra_files
- new filter str2date + tests
> tide java and str2date

- timApp/i18n/messages.fi.xlf
- timApp/i18n/messages.sv.xlf
- timApp/static/scripts/tim/user/user-menu.component.ts
Adds the menu option 'My TIM settings' to the user menu in the top header bar.
> Add link to user's TIM settings in tim-user-menu

- timApp/modules/cs/static/chartjs/timonedata.js
- timApp/package-lock.json
This version suits better if one want more control for data (more than 2 dataset, user colors).
> Feature chart js colors

- timApp/modules/cs/cs.py
- timApp/modules/cs/js/csPlugin.ts
- timApp/static/stylesheets/csRun.scss
New iframes attribute to csPlugin, see: <https://tim.jyu.fi/view/tim/ohjeita/csPlugin#iframes>.
Shows program generated html files in separate iframes.
> show program generated htmls in iframes

- timApp/modules/cs/cs.py
- timApp/modules/cs/iframes.py
- timApp/modules/cs/js/csPlugin.ts
- timApp/modules/cs/languages.py
nyt olisi mm. sandbox optio.
ohjeet cspluginin ohjeissa
en ymmärrä miksi testit feilaa
> Feature program output html to iframe

- timApp/modules/cs/js/csPlugin.ts
- timApp/modules/cs/tauno/tauno.css
- timApp/modules/cs/tauno/tauno.html
- timApp/modules/cs/tauno/tauno.js
Finally UNDO for tauno.
File names changes to tauno.xxx and if everything works all other tauno files could be removed
> Feature tauno undo
